GoogleCloudPlatform/guest-test-infra

- container_images/gotest/Dockerfile
- container_images/gotest/main.sh
sample coverage details
https://00e9e64bacf4dd0158a308f352f6259afec2139d17450b646d-apidata.googleusercontent.com/download/storage/v1/b/oss-prow/o/pr-logs%2Fpull%2FGoogleCloudPlatform_osconfig%2F53%2Fosconfig-presubmit-gotest%2F1166860625792471040%2Fartifacts%2Fcoverage.html?qk=AD5uMEvrAYyezMxsk4GjaUB0Iea7n8Ed8re3WVOxzZyAqkfSrBOBzYkBOG35mAHwNIoT7AtGPW_qbM2Sqtm2SV0H_McZQypPgXMyR76RyjhW9Uch4phbhvqbawH1HxiKXBvjiWAKC5JYEmtoWyw7IG2fsu8H1iXy9LOhVHTrdLbBFU_m1nV9twkESk6JVMcJLMIPJD417LyRYFygr__nmji9ZM1HNob7GaWw6rbbqZ8DA9hRt-KOzrbeTXYZwFraDH_8AKBydJp1rU1lOEm0togyEcCUlcLn7XaxSCVaX9fGtyBX9hk5OKNjBSYjTE6bu5l6BVFyXv0dMIIpgm9L0NfsGISl3doYGMxOGUVaRQh3l-_pE0r7z19XlLdxUPYACEO_XTX3WihDXSaJc_wyZb_YLOMygDl6I8nTAeKxvlpoQymDKPJBQb1hCR3LqG3qh2PEZNUklPyRL6WqJQk3jYsPsUIJJuEEVFCMC2PNHUD4w2f7X55CzVVHf4g-PHTSosGK4Iz-g4 …
> Get code coverage details

- packagebuild/daisy_startupscript_rpm.sh
the old URL used to redirect to this one, but the redirection was discontinued. see iusrepo/announce#18
> update IUS RPM URL

- container_images/cloudbuild.yaml
- container_images/gointegtest/run_integ_tests.sh
* fix cloudbuild.yaml
* don't abort test runner if tests fail, we want the results
> small fixes for gointegtest

- concourse/concourse-helm-values.yaml
The values we will use to create the Concourse cluster using the helm chart at https://github.com/concourse/concourse-chart
> add helm chart values

- concourse/pipelines/pipeline-set-pipeline.yaml
Fix typo in repo and branch name.
> add two new pipeline in set-pipeline

- packagebuild/common.sh
> multiarch package builder

- concourse/pipelines/guest-package-build.yaml
- concourse/tasks/gcloud-inject-package.yaml
- concourse/tasks/generate-package-version.yaml
* rename inject steps for oslogin build
* correct ash-supported shell arithmetic in generate-package-version
* correct reference to gcloud/alpine image
> guest-package-build bugfixes

- concourse/pipelines/linux-image-build-almalinux.yaml
- concourse/pipelines/linux-image-build-rhel.yaml
- concourse/pipelines/pipeline-set-pipeline.yaml
> Move almalinux to its own pipeline.

- imagetest/fixtures.go
- imagetest/testworkflow.go
- imagetest/testworkflow_test.go
depends on #98 
add test fixtures
> add test fixtures

- imagetest/cmd/manager/main.go
- imagetest/testworkflow.go
* create a per-project output bucket, as daisy does
* print the junit output at the end
> create per-project output bucket

- imagetest/fixtures.go
- imagetest/test_suites/image_boot/image_boot_test.go
- imagetest/test_suites/image_boot/setup.go
- imagetest/test_suites/image_validation/image_license_test.go
image_boot git:(image-test-secureboot) /out/manager -project hanga-testing -zone us-west1-c -images projects/rhel-cloud/global/images/rhel-8-v20210420
2021/04/28 22:14:31 imagetest: Done with setup
runTestWorkflow: running image_validation on rhel-8-v20210420 (ID 331l4)
runTestWorkflow: running image_boot on rhel-8-v20210420 (ID qb0h0)
````<testsuites name="" errors="0" failures="0" tests="0" time="0">
<testsuite name="image_validation-rhel-8-v20210420" tests="4" failures="0" errors="0" disabled="0" skipped="0" time="0">
<testcase classname="" name="TestHostname" time="0"></testcase>
<testcase classname="" name="TestFQDN" time="0"></testcase>
<testcase classname="" name="TestHostKeysGeneratedOnce" time="1.42"></testcase>
<testcase classname="" name="TestCustomHostname" …
```
> add secureboot test

- concourse/pipelines/linux-image-build.yaml
Depends on: https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1621
> Add Rocky Linux 8 build

- imagetest/cmd/manager/main.go
docker run cloud-image-tests [...] -images rhel-8 -filter image_validation
```
2021/05/05 19:27:06 imagetest: Done with setup
runTestWorkflow: running image_validation on rhel-8 (ID q50jv)
<testsuites name="" errors="0" failures="0" tests="0" time="0">
<testsuite name="image_validation-rhel-8" tests="6" failures="2" errors="0" disabled="0" skipped="0" time="0">
<testcase classname="" name="TestHostname" time="0.02"></testcase>
<testcase classname="" name="TestFQDN" time="0.02"></testcase>
<testcase classname="" name="TestHostKeysGeneratedOnce" time="0.36">
<failure type="">    image_validation_test.go:162: Hashes changed after restarting guest agent</failure>
</testcase>
<testcase classname="" name="TestArePackagesLegal" time="0.22">
<failure type="">    license_test.go:179: Found illegal …
```
> support test filter

- imagetest/test_suites/image_validation/package_test.go
- imagetest/test_suites/image_validation/setup.go
confirm the guest environment packages are installed
> add guest packages test

- concourse/pipelines/guest-package-build.yaml
- concourse/tasks/guest-package-build.yaml
* expose git_ref parameter instead of hardcoding to 'master'
* add artifact registry plugin builds to pipeline
tested working
> Artifact registry plugin builds

- concourse/pipelines/linux-image-build.yaml
- concourse/tasks/image-test.yaml
Test in concourse:
http://localhost:8080/teams/main/pipelines/hanga-test/jobs/image-test-centos-7/builds/1
```
waiting for docker to come up...
Pulling gcr.io/gcp-guest/cloud-image-tests@sha256:a2fa4b871758d7195025c898b5ea8b33a6283a82ccddf4f56c12b8157ebb7bf2...
sha256:a2fa4b871758d7195025c898b5ea8b33a6283a82ccddf4f56c12b8157ebb7bf2: Pulling from gcp-guest/cloud-image-tests
fa7045767063: Pulling fs layer
9ead6935b54c: Pulling fs layer
fa7045767063: Download complete
fa7045767063: Pull complete
9ead6935b54c: Verifying Checksum
9ead6935b54c: Download complete
9ead6935b54c: Pull complete
Digest: sha256:a2fa4b871758d7195025c898b5ea8b33a6283a82ccddf4f56c12b8157ebb7bf2
Status: Downloaded newer image for gcr.io/gcp-guest/cloud-image-tests@sha256:a2fa4b871758d7195025c898b5ea8b33a6283a82ccddf4f56c12 …
```
> add e2e-test job and task

- concourse/pipelines/guest-package-build.yaml
- concourse/tasks/gcloud-promote-package.yaml
* combine image test steps to inject step
* inject directly to staging instead of unstable for guest-agent
* add promote task
* add guest-agent promote to stable job
* add groupings
> add package promotion

- concourse/pipelines/guest-package-build.yaml
> use 'main' for guest-agent

- go.mod
- go.sum
- imagetest/cmd/manager/main.go
- imagetest/test_suites/security/image_security_test.go
- imagetest/test_suites/security/setup.go
```
<testsuites name="" errors="0" failures="0" tests="0" time="0">
<testsuite name="security-ubuntu-2004-lts" tests="3" failures="0" errors="0" disabled="0" skipped="0" time="0">
<testcase classname="" name="TestKernelSecuritySettings" time="0"></testcase>
<testcase classname="" name="TestAutomaticUpdates" time="0.02"></testcase>
<testcase classname="" name="TestPasswordSecurity" time="0"></testcase>
</testsuite>
<testsuite name="security-ubuntu-1604-lts" tests="3" failures="0" errors="0" disabled="0" skipped="0" time="0">
<testcase classname="" name="TestKernelSecuritySettings" time="0"></testcase>
<testcase classname="" name="TestAutomaticUpdates" time="0.02"></testcase>
<testcase classname="" name="TestPasswordSecurity" time="0"></testcase>
</testsuite>
<testsuite …
```
> add security image test

- concourse/pipelines/linux-image-build.yaml
- concourse/pipelines/partner-image-export.yaml
> Add staging/oslogin staging publish tasks.

- concourse/pipelines/linux-image-build.yaml
Open to other suggestions but this makes it easier to troubleshoot failures IMO.
> Run image test on correct image and publish to testing on build.

- OWNERS
Adding myself and Lawrence to the owners file
> Adding myself and Lawrence to the owners file

- imagetest/test_suites/image_boot/setup.go
- imagetest/test_suites/image_boot/shutdown_test.go
```
image_boot git:(image-test-shutdown-test) ✗ /manager -project hanga-testing -zone us-west1-c -images projects/debian-cloud/global/images/family/debian-10
2021/06/03 20:05:42 imagetest: Done with setup
runTestWorkflow: running image_boot on debian-10 (ID vqbhg)
<testsuites name="" errors="0" failures="0" disabled="0" skipped="0" tests="1" time="0">
<testsuite name="image_boot-debian-10" tests="1" failures="0" errors="0" disabled="0" skipped="0" time="0">
<testcase classname="" name="TestGuestShutdownScript" time="0"></testcase>
</testsuite>
</testsuites>
```
> add shutdown script test

- concourse/pipelines/pipeline-set-pipeline.yaml
- concourse/pipelines/windows-image-build.yaml
- concourse/tasks/daisy-build-images-windows.yaml
- Added windows-image-build pipeline
- Added windows-image-build.yaml for windows-image-build pipeline
- Added daisy-build-image-windows.yaml to pass all of the needed windows build variables.
> Adding Windows Server image builds 

- imagetest/test_suites/disk/disk_resize_test.go
- imagetest/test_suites/image_boot/image_boot_test.go
- imagetest/test_suites/image_validation/license_test.go
- imagetest/test_suites/network/mtu_test.go
- imagetest/test_suites/security/image_security_test.go
> Fix several image tests.

- imagetest/test_suites/image_boot/setup.go
- imagetest/test_suites/security/image_security_test.go
> Skip secure boot tests for Debian 9.

- concourse/pipelines/guest-package-build.yaml
add job for promoting oslogin packages to stable repos
> promote oslogin

- concourse/pipelines/guest-package-build.yaml
> add oslogin staging promotion

- imagetest/test_suites/image_boot/image_boot_test.go
> Switch to modern efivars file.

- concourse/pipelines/linux-image-build.yaml
Goes with https://github.com/GoogleCloudPlatform/compute-image-tools/pull/1695
> Add RHEL 8.4 for SAP build.

- concourse/pipelines/guest-package-build.yaml
add promote-to-staging and promote-to-stable jobs for AR plugin builds
> add AR promotions

- imagetest/test_suites/ssh/image_ssh_test.go
Some extract check on ssh remote vm.
```
2021/07/26 19:01:44 imagetest: Done with setup
runTestWorkflow: running ssh on debian-9 (ID 8435m)
<testsuites name="" errors="0" failures="0" disabled="0" skipped="0" tests="2" time="0">
<testsuite name="ssh-debian-9" tests="2" failures="0" errors="0" disabled="0" skipped="0" time="0">
<testcase classname="" name="TestSSH" time="0.29"></testcase>
<testcase classname="" name="TestEmptyTest" time="0"></testcase>
</testsuite>
</testsuites>
```
> add local user check

- imagetest/test_suites/metadata/metadata_test.go
- imagetest/utils/test_utils.go
```
<testsuite name="metadata-debian-10" tests="5" failures="0" errors="0" disabled="0" skipped="0" time="0">
<testcase classname="" name="TestTokenFetch" time="0"></testcase>
<testcase classname="" name="TestMetaDataResponseHeaders" time="0"></testcase>
<testcase classname="" name="TestGetImplicitMetadata" time="0.01"></testcase>
<testcase classname="" name="TestGetMetadataDirectory" time="0"></testcase>
<testcase classname="" name="TestGetMetaDataUsingIP" time="0"></testcase>
</testsuite>
</testsuites>
```
> Image test medadata 2

- imagetest/Dockerfile
> add ssh-keygen to CIT image

- imagetest/test_suites/hostkey/hostkey_pubish_test.go
- imagetest/test_suites/ssh/image_ssh_test.go
- imagetest/test_suites/ssh/setup.go
- imagetest/utils/test_utils.go
This test utilize the ssh test setup, so move from test_suite hostkey to ssh. It compare the hostkey on disk for two vms.
> add test TestHostKeysAreUnique

- concourse/pipelines/linux-image-build.yaml
> Remove test steps until tests are stable.

- imagetest/README.md
- imagetest/test_suites/README.md
> CIT: add test docs

- concourse/pipelines/linux-image-build.yaml
* add daily-time resource to linux-image-build pipeline
* add triggering get on daily-time resource to all build jobs in linux-image-build pipeline
> build linux images daily

- concourse/pipelines/linux-image-build.yaml
add image tests at the end of publish-to-testing jobs. failure of tests will fail the publish job, so also add retries.
> add image testing

- concourse/pipelines/bare-metal-image-build.yaml
- concourse/pipelines/debian-worker-image-build.yaml
- concourse/pipelines/linux-image-build.yaml
- concourse/pipelines/partner-image-export.yaml
This is part of the overall image pipeline cutover. This PR focuses on Linux related image build changes.
Hold until ready to cutover.
/hold
> Cutover image pipeline - Linux related image builds

- concourse/pipelines/artifact-releaser-autopush.yaml
- concourse/tasks/gcloud-promote-package.yaml
Update the PubSub topic to artifact releaser prod topic. Should merge when ready to cutover.
/hold
> Cutover pubsub topic

- imagetest/fixtures.go
- imagetest/test_suites/network/alias_ip_test.go
- imagetest/test_suites/network/multinic_minimal_network_test.go
- imagetest/test_suites/network/setup.go
* merge tests to 2 VMs
* test combination of alias routes + multinic together
* refactor network/setup.go for readability
> fix network test

- imagetest/test_suites/oslogin/oslogin_test.go
- imagetest/test_suites/oslogin/setup.go
Previous PR got merged right as I was committing these changes to the branch. These changes are based on feedback from the previous PR.
> Fixes for OS Login tests that got missed.

- imagetest/test_suites/disk/setup.go
- imagetest/test_suites/image_validation/image_validation_test.go
- imagetest/test_suites/image_validation/license_test.go
- imagetest/test_suites/image_validation/package_test.go
- imagetest/test_suites/network/dhcp_test.go
- imagetest/test_suites/security/image_security_test.go
- imagetest/testworkflow.go
* add skips to unsupported tests
* add missing bad language license
> test fixes for SLES

- concourse/tasks/image-test-args.yaml
- concourse/tasks/image-test.yaml
temporarily disable oslogin test family in all prod testing
> disable OS Login tests

- concourse/pipelines/windows-image-build.yaml
Updating the Windows pipeline to use secret manager
/hold
> Updating the Windows pipeline to use secret manager

- concourse/pipelines/windows-image-build.yaml
- concourse/tasks/daisy-build-images-windows-sql.yaml
Add sql-2012-enterprise-windows-2012-r2-dc to the Concouse pipeline. This is part of the Concourse pipeline migration.
/cc @bkatyl
> Add sql-2012-enterprise-windows-2012-r2-dc

- concourse/tasks/daisy-build-images-windows-sql.yaml
To fix failed Concourse test run: `/jobs/build-sql-2012-enterprise-windows-2012-r2-dc/builds/3`
/cc @bkatyl
> Fix windows sql build task

- concourse/pipelines/windows-image-build.yaml
Add the rest of SQL server builds and change release to test flag to true in the base windows image.
/cc bkatyl
> Add SQL server builds/ releases

- concourse/pipelines/windows-image-build.yaml
add `skip_download` flag to all get steps referencing a GCS resource
> add skip_download to windows builds

- imagetest/test_suites/image_validation/license_test.go
I'm looking at you perl-Module-Build
> Some packages have license info in their README file.

- concourse/pipelines/windows-image-build.yaml
- Update triggered resources so the jobs are linked to resources more meaningful to the jobs
- Add skip_download: "true" to publish steps to avoid unnecessary download
/cc @bkatyl
/cc @hopkiw
/hold
> Update triggered resources

- concourse/pipelines/windows-image-build.yaml
Add missing vars to the container workflow.
/cc @bkatyl
> Add missing vars to the container workflow

- concourse/tasks/daisy-build-images-windows-container.yaml
Fix container task var.
/cc @bkatyl
> Fix container task var

- concourse/tasks/daisy-build-images-windows-container.yaml
Fix missing var in container task.
> Fix missing var in container task

- concourse/pipelines/windows-image-build.yaml
> Update gcs naming to match publish workflows

- concourse/pipelines/guest-package-build.yaml
- concourse/tasks/get-last-stable-tag.yaml
- concourse/tasks/publish-time-since.yaml
- container_images/concourse-metrics/Dockerfile
- container_images/concourse-metrics/cmd/publish-time-since/main.go
- container_images/concourse-metrics/pkg/requests/requests.go
* Publish `stable` and `stable-YYYYMMDD` tags on each stable promotion
* Publish a time-since-last-release metric
> Publish stable tags for guest-agent

- concourse/pipelines/container-build.yaml
missed adding to the pipeline in #335
> add JSONnet container build

- container_images/fly-validate-pipelines/main.sh
make output of presubmit useful for reviewers
> tee jsonnet output

- concourse/pipelines/linux-image-build.jsonnet
- concourse/templates/gcp-secret-manager.libsonnet
- concourse/templates/lego.libsonnet
* use lego instead of certbot
* add optional output path param to the getsecret task template
* make daily image builds an optional parameter
> use lego instead of certbot in rhui build

- concourse/pipelines/linux-image-build.jsonnet
This task needed updating to stop using creds, go ahead and templatize it rather than cloning a new variant.
> use template result task

- concourse/pipelines/linux-image-build.jsonnet
replace more tasks with task templates that don't reference the credentials input
> linux-image-build: use workload ID in publish tasks

- concourse/pipelines/windows-image-build.yaml
Add SQL 2017/2019 on server 2022 build jobs
/cc @bkatyl
/hold
> Add SQL 2017/2019 on server 2022 build jobs

- concourse/pipelines/guest-package-build.yaml
- concourse/pipelines/linux-image-build.jsonnet
- concourse/pipelines/partner-image-export.yaml
- container_images/gointegtest/integ-test-all.wf.json
- packagebuild/workflows/build_el9.wf.json
Also, add Debian 11 to our integ tests.
> Add pre-release builds/tests for CentOS Stream 9.

- concourse/pipelines/linux-image-build.jsonnet
vars field is for workflow variables, we actually need to set a top level arg to daisy
> put gcspath arg in correct location

- concourse/pipelines/container-build.jsonnet
Same error as in https://github.com/GoogleCloudPlatform/guest-test-infra/pull/386
> Fix `sh: illegal option - `

- concourse/pipelines/container-build.jsonnet
This was motivated by https://github.com/GoogleCloudPlatform/guest-test-infra/pull/401 where I added SHA tags for Daisy; @hopkiw  suggested that I apply this to all containers.
> Container builds: Add a tag with commit sha

- concourse/pipelines/container-build.jsonnet
Following this PR, the daisy artifacts will be published to the following locations:
- Container image:
- Every build is tagged with the commit's SHA
- If the tests pass, then the `release` and `latest` tags are applied to the build
- Windows, Linux, and OSX binaries:
- If tests pass, upload to `gs://compute-image-tools/{latest,release}/{linux,windows,darwin}`
This is consistent with the [legacy cloud build](https://github.com/GoogleCloudPlatform/compute-image-tools/blob/v20220209/cli_tools_cloudbuild.yaml#L30-L33) configuration that used to build daisy.
The following tests are added in this PR:
- Run all workflows in [compute-daisy/daisy_integration_tests](https://github.com/GoogleCloudPlatform/compute-daisy/tree/master/daisy_integration_tests) using the daisy test runner.
- Run one …
> Daisy build: Add pre-release tests

- concourse/templates/lego.libsonnet
tell LEGO how to confirm the DNS entry is updated
> short circuit dns propagation

- concourse/pipelines/windows-image-build.jsonnet
Removing underscore replacement since the files currently use dashes
> Removing underscore replacement since the files currently use dashes

- concourse/pipelines/linux-image-build.jsonnet
add rocky-optimized-gcp-8; amend rollout rate for rhui
> add rocky linux optimized for gcp

- concourse/pipelines/artifact-releaser-test.yaml
- concourse/pipelines/guest-package-build.yaml
- concourse/tasks/gcloud-package-operation.yaml
Upload ARM apckages.
Hold until the "upload" operation supports multiple files uploading.
> upload ARM packages

- concourse/tasks/image-test-args.yaml
> [image-test-args] fix a minor typo

- concourse/pipelines/windows-image-build.jsonnet
This will allow us to build and  publish images to the internal environment.
> Update windows pipeline to support internal env

- concourse/pipelines/guest-package-build.jsonnet
> Add Windows SSH to guest-package-build.

- concourse/pipelines/guest-package-build.jsonnet
there was a typo in the version used in promote jobs, so i've extracted the version from build jobs and used it as a template.
> extract generate-timestamp to template

- concourse/pipelines/windows-image-build.jsonnet
This makes staging the only manual step in Concourse.
> Update triggers in windows pipeline

- concourse/pipelines/partner-image-validations.jsonnet
* comment out not-yet-existing families
* add groups for ease of UI navigation
> add groups to partner validations

- packagebuild/daisy_startupscript_deb.sh
- packagebuild/daisy_startupscript_rpm.sh
inspect built packages before completing the workflow. produces useful debug information in logs.
> logging package contents

- concourse/pipelines/partner-image-validations.jsonnet
* parameter for GCS bucket in imagevalidationjob template
* add suse-cloud-testing/sles-15 job
> add sles validations

- concourse/pipelines/windows-image-build.jsonnet
- concourse/templates/daisy.libsonnet
hold until the corresponding build files on compute-image-tools are merged.
> build & publish windows-install-media 

- concourse/pipelines/windows-image-build.jsonnet
Reflects some changes made when publishing secrets for easier reference later.
> Update secret used by SQL22

- concourse/pipelines/windows-image-build.jsonnet
Adds "client" environment to builds; removes excess publish job as I don't think it's needed anymore.
> Update Windows pipeline to include new environment

- README.md
- container_images/README.md
- packagebuild/README.md
Add README files for the container images and package build workflows
> add more READMEs

- concourse/pipelines/linux-image-build.jsonnet
* don't run CIT on RHUI images
* make prod publish after testing publish
> update RHUI image builds

- packagebuild/workflows/build_deb10.wf.json
- packagebuild/workflows/build_deb11.wf.json
- packagebuild/workflows/build_deb11_arm64.wf.json
- packagebuild/workflows/build_deb9.wf.json
- packagebuild/workflows/build_el6.wf.json
- packagebuild/workflows/build_el7.wf.json
- packagebuild/workflows/build_el8.wf.json
- packagebuild/workflows/build_el8_arm64.wf.json
- packagebuild/workflows/build_el9.wf.json
- packagebuild/workflows/build_el9_arm64.wf.json
I believe this is the correct definition location for timeouts as the previous definition was being superceded by the default 10m timeout on the parent task.
> Move timeout definition for package build steps

- packagebuild/workflows/build_deb10.wf.json
- packagebuild/workflows/build_deb11.wf.json
- packagebuild/workflows/build_deb11_arm64.wf.json
- packagebuild/workflows/build_deb9.wf.json
- packagebuild/workflows/build_el6.wf.json
- packagebuild/workflows/build_el7.wf.json
- packagebuild/workflows/build_el8.wf.json
- packagebuild/workflows/build_el8_arm64.wf.json
- packagebuild/workflows/build_el9.wf.json
- packagebuild/workflows/build_el9_arm64.wf.json
- packagebuild/workflows/build_package.wf.json
Fixes the 10m timeout superceding the previous 20m adjustment.
> Update wait-for-build timeout for package builds

- concourse/pipelines/linux-image-build.jsonnet
Make a test image build to add the syft arg and verify manually.
After verifying this, the syft arg will be added to the other image builds.
> syft test build

- concourse/pipelines/linux-image-build.jsonnet
Fix minor syntax issue in build
> Fix double colon syntax

- concourse/templates/daisy.libsonnet
Add local var sbom_destination to the daisy template.
> Add sbom dest local var

- concourse/pipelines/linux-image-build.jsonnet
- concourse/templates/daisy.libsonnet
Use std.strReplace to create sbom_destination variable for final sbom file export.
> SBOM destination by replacing gcs_url suffix

- concourse/templates/daisy.libsonnet
std strReplace in libsonnet was not succeeding, reverting the bug until the fix is found.
> Revert sbom destination bug

- concourse/pipelines/windows-image-build-staging.jsonnet
Generate build id for windows staging
> add id generation to windows staging

- concourse/pipelines/linux-image-build.jsonnet
Include comments for recent changes with the common build id.
> Add comments for common id generation

- concourse/pipelines/pipeline-set-pipeline.yaml
- concourse/pipelines/windows-image-build-staging.jsonnet
Re-adding to pipeline definitions after fixing env issue.
> Re-introduce Windows staging env

- concourse/pipelines/windows-image-build-staging.jsonnet
- concourse/pipelines/windows-image-build.jsonnet
Adds new workflows in another PR to build pipelines
> Add CE Docker builds to Windows pipeline

- concourse/pipelines/windows-image-build-staging.jsonnet
- concourse/pipelines/windows-image-build.jsonnet
Reflects changes in another PR to fix naming convention.
> Update workflow names in pipeline def

- packagebuild/daisy_startupscript_deb.sh
- packagebuild/daisy_startupscript_goo.sh
- packagebuild/daisy_startupscript_rpm.sh
Don't redirect stderr to /dev/null so the errors are logged (if that's the case) and remove leading / on the gcs bucket url (gsutil fails to copy if the url looks like cs://path//to-file).
> package build(sbom): sbomutil fetching

- packagebuild/test_build.sh
This script builds packages for any of supported platforms, from any repository or commit and supports defining versions.
> Add package build script

- packagebuild/common.sh
- packagebuild/daisy_startupscript_deb.sh
- packagebuild/daisy_startupscript_rpm.sh
This change moves the implementation of the steps to deploy sbom and generating the actual sbomutil to common.sh and adapts rpm and deb scripts to call the routines defined in there.
> sbom: move it all to common.sh

- concourse/pipelines/linux-image-build.jsonnet
Add SBOM generation for debian image builds
> Debian SBOM publishing

- concourse/pipelines/windows-image-build.jsonnet
> Windows sbom resource

- packagebuild/daisy_startupscript_goo.sh
use file name as package name as both are same
> Fix googet build failure due to invalid json passed to jq

- concourse/pipelines/partner-image-validations.jsonnet
Start looking at SLES prod images (we don't yet have stable test images.
> Cleanup partner image validation pipeline

- imagetest/testworkflow.go
With that we can easily determine/check the time spent for each test by simply looking at the "finished" lines.
> testworkflow: display time delta to log

- imagetest/test_suites/image_validation/clock_test.go
- imagetest/test_suites/network/dhcp_test.go
- imagetest/utils/test_utils.go
Check if the dhcp IPv4 is found using commands. If any of the cases pass, pass the test.
> Use commands for DHCP test

- imagetest/fixtures.go
- imagetest/testworkflow.go
- imagetest/testworkflow_test.go
Allow multiple disks to be added in the create VM step
> Support multiple disks in a VM

- imagetest/test_suites/disk/disk_resize_test.go
- imagetest/test_suites/image_boot/image_boot_test.go
- imagetest/test_suites/network/alias_ip_test.go
Fix the build by using fatalf instead of fatal
> Change fatal to fatalf

- imagetest/fixtures.go
- imagetest/fixtures_test.go
- imagetest/test_suites/storage_perf/setup.go
- imagetest/testworkflow.go
- imagetest/testworkflow_test.go
Add support for test vms with multiple disks
> Support vm with multiple disks

- imagetest/test_suites/storage_perf/iops_print_test.go
- imagetest/test_suites/storage_perf/iops_read_test.go
- imagetest/test_suites/storage_perf/setup.go
- imagetest/test_suites/storage_perf/storage_perf_utils.go
Add mount steps, and eventually fio test outputs to the storage perf test.
> fio read test

- imagetest/README.md
Working to set a convention for repo consistency and maintainability
> Add guidance on writing tests for Linux+Windows

- imagetest/test_suites/image_boot/image_boot_test.go
Splits necessary tests into separate functions in order to run the same battery against Linux and Windows
> Update image_boot test to support Windows boot testing

- imagetest/test_suites/storage_perf/iops_read_test.go
- imagetest/test_suites/storage_perf/setup.go
- imagetest/test_suites/storage_perf/startupscripts/install_fio.ps1
- imagetest/test_suites/storage_perf/startupscripts/install_fio.sh
- imagetest/test_suites/storage_perf/storage_perf_utils.go
Work on generic startup scripts to install fio before tests run, and work on windows support
> add startup scripts

- imagetest/utils/test_utils.go
Fixes wrong return value that was added in on thursday
> Fix test_utils return on runtime

- imagetest/test_suites/imageboot/image_boot_test.go
Replaces runtime import with helper from utils
> Update Windows conditionals in boottest

- imagetest/fixtures.go
- imagetest/test_suites/storageperf/iops_read_test.go
- imagetest/test_suites/storageperf/setup.go
- imagetest/test_suites/storageperf/startupscripts/install_fio.ps1
- imagetest/test_suites/storageperf/storage_perf_utils.go
> Fio windows testing

- imagetest/test_suites/storageperf/iops_read_test.go
- imagetest/test_suites/storageperf/iops_write_test.go
- imagetest/test_suites/storageperf/setup.go
- imagetest/test_suites/storageperf/startupscripts/install_fio.ps1
- imagetest/test_suites/storageperf/storage_perf_utils.go
Still working on windows fio write: seems like some parameters might be causing an error if the exact same parameters from read are used
> write iops

- imagetest/test_suites/storageperf/iops_read_test.go
- imagetest/test_suites/storageperf/iops_write_test.go
- imagetest/test_suites/storageperf/setup.go
- imagetest/test_suites/storageperf/storage_perf_utils.go
- imagetest/utils/test_utils.go
Add write and read throughput testing to storageperf
To avoid merge conflicts with #782 it is probably easiest to merge this PR, instead of merging #776
> Throughput testing

- imagetest/test_suites/shapevalidation/sysinfo_linux.go
Previous test mistakenly counted all CPUs and NUMA nodes regardless of availability.
> Only count CPUs and NUMA nodes that are online on linux

- imagetest/test_suites/sql/setup.go
- imagetest/test_suites/sql/sql_test.go
- imagetest/test_suites/sql/startupscripts/remote_auth_client_setup.ps1
- imagetest/test_suites/sql/startupscripts/remote_auth_server_setup.ps1
Start of SQL Test suite, more to come but incrementally adding tests.
> Add SQL Power Plan and Remote Connectivity Tests

- imagetest/test_suites/storageperf/iops_read_test.go
- imagetest/test_suites/storageperf/iops_write_test.go
- imagetest/test_suites/storageperf/setup.go
- imagetest/test_suites/storageperf/storage_perf_utils.go
Add pd balanced tests to storageperf
> pd balanced tests

- imagetest/test_suites/hotattach/hot_attach_test.go
- imagetest/test_suites/hotattach/setup.go
- imagetest/test_suites/storageperf/setup.go
- imagetest/test_suites/storageperf/storage_perf_utils.go
Corrections on el7 hotattach test, add more machine types to storageperf
> Hotattach fix, storageperf machine types

- imagetest/cmd/wrapper/main.go
- imagetest/fixtures.go
- imagetest/testworkflow.go
- imagetest/testworkflow_test.go
- imagetest/utils/test_utils.go
This change should CIT tests to pass if either serial output matches or the guest attribute is set.
> Add guest attributes

- imagetest/testworkflow.go
Investigate guest attribute bug with metadata shutdown script test
> revert guest attribute

- concourse/pipelines/linux-image-build.jsonnet
Generated step:
```
{
"name": "publish-to-prod-debian-10",
"on_failure": {
"config": {
"image_resource": {
"source": {
"debug": true,
"google_auth": true,
"repository": "gcr.io/gcp-guest/concourse-metrics",
"tag": "latest"
},
"type": "registry-image-forked"
},
"platform": "linux",
"run": {
"args": [
"--project-id=gcp-guest",
"--zone=us-central1-a",
"--pipeline=linux-image-build",
"--job=publish-to-prod-debian-10",
"--task=publish-job-result",
"--result-state=failure",
"--start-timestamp=((.:start-timestamp-ms))",
"--metric-path=concourse/job/duration"
],
"path": "/publish-job-result"
}
},
"task": "failure"
},
"on_success": {
"config": {
"image_resource": {
"source": {
"debug": true,
"google_auth": true,
"repository": "gcr.io/gcp-guest/concourse-metrics",
"tag": "latest"
},
"type": …
```
> Add CIT to publish pipeline, without removing the publish step

- concourse/README.md
- concourse/pipelines/README.md
> docs: Update README.md with correct link to Kaniko Repository & Fix typos

- imagetest/fixtures.go
> Check quota less frequently

- imagetest/test_suites/shapevalidation/setup.go
> Exempt EL7 from C3D shape validation

- imagetest/test_suites/storageperf/setup.go
- imagetest/test_suites/storageperf/storage_perf_utils.go
Perf targets from https://cloud.google.com/compute/docs/disks/performance#t2a_vms
> Test pdbalanced performance on ARM64 images in storageperf

- imagetest/test_suites/storageperf/setup.go
Some failures on the perf test grid this morning are from this.
/cc @jjerger @zmarano @drewhli @koln67
> Fix architecture check and vm zone in storage perf.

- imagetest/fixtures_test.go
- imagetest/test_suites/network/setup.go
- imagetest/testworkflow_test.go
Change the network test reboot command slightly and add guest attribute tests
> Guest attribute testing and network reboot setup

- imagetest/test_suites/network/setup.go
Use the vm config struct for the vm name
> Quick style fix

- imagetest/test_suites/hotattach/setup.go
Passed when I ran locally
/cc @jjerger @zmarano @drewhli @koln67
> Stop skipping hotattach on arm

- concourse/pipelines/guest-package-build.jsonnet
The reason for this change is that the promotion will now be handled by Artifact Releaser, so these steps now serve no purpose.
> Remove unnecessary promote-to-stable steps from guest package build pipeline

- imagetest/test_suites/networkperf/setup.go
> Set NetworkPerformanceTier to TIER_1 on the t1 client vm

- concourse/pipelines/windows-image-build-staging.jsonnet
- concourse/pipelines/windows-image-build-standard.jsonnet
- concourse/pipelines/windows-image-build.jsonnet
Confused these for something else; CE is not actually needed anymore either.
> Remove remaining container builds from Concourse

- imagetest/README.md
> Warn about mixing GA and beta instance APIs when creating test suites

- concourse/pipelines/guest-package-build.jsonnet
Differently to the main branch this pipeline doesn't publish the final package but limits to building the package and derived images and runs the CIT tests.
> guest agent: add a pipeline for a development branch

- concourse/pipelines/windows-image-build-mbr.jsonnet
> Re-enable publish steps to allow testing

- imagetest/test_suites/hotattach/hot_attach_test.go
Flush the writer and sync the file to ensure the hotattach disk attach call does not happen while the file write is still in progress.
> File sync call

- imagetest/test_suites/networkperf/performance_test.go
- imagetest/test_suites/networkperf/startupscripts/netclient_startup.sh
- imagetest/test_suites/networkperf/startupscripts/windows_clientstartup.ps1
Retry GET for network results and POST for network results three times each with an increasing delay after each failed request.
> Retry network performance results fetch three times

- concourse/pipelines/container-build.jsonnet
/cc @zmarano @ChaitanyaKulkarni28
> Build and publish windows upgrade test container

- concourse/pipelines/container-build.jsonnet
> Correct windows upgrade tests dockerfile path

- concourse/pipelines/windows-image-build-mbr.jsonnet
Excluding test suites not intended for Windows Server
> Update excluded tests in Windows cit grouping

- container_images/cleanerupper/go-cleanerupper/cleanerupper.go
- container_images/cleanerupper/go-cleanerupper/cleanerupper_test.go
- container_images/cleanerupper/main.go
/cc @zmarano @jjerger @koln67 @drewhli
> Don't delete resources named do-not-delete

- concourse/tasks/render-templates.yaml
> Define guest-image-private within render-templates.yaml

- concourse/pipelines/pipeline-set-pipeline.yaml
- concourse/tasks/render-templates.yaml
> Use guest-image-private resource_type

- concourse/tasks/render-templates.yaml
> Remove tag from registry-image-private fetch

- concourse/pipelines/pipeline-set-pipeline.yaml
> Add tag to resource_type in pipeline-set-pipelines

- imagetest/test_suites/packagevalidation/package_test.go
> Check for google-cloud-cli on all (non suse) distros, falling back to google-cloud-sdk if neccessary

- imagetest/test_suites/README.md
/cc @koln67 @drewhli 
Didn't notice this until after approval
> Correct default statement in customhostname readme section

- imagetest/test_suites/security/image_security_test.go
Add support for checking ubuntu's sshd_config: rather than parsing /etc/ssh/sshd_config, derive the effective config and check that
Add better support for SUSE/SLES by skipping only the parts of the tests where these diverge from our expectations, rather than skipping the whole test
/cc @zmarano @koln67 @elicriffield
> Add better partner support in the security suite.

- imagetest/test_suites/security/image_security_test.go
> Report actual and expected values for autoclean interval test failures

- imagetest/test_suites/security/image_security_test.go
> Dump apt config from apt rather than parsing selected config files

- imagetest/test_suites/README.md
> Document shapevalidation

- imagetest/test_suites/hostnamevalidation/hostname_validation_test.go
> Add missing hostnamevalidation exceptions for opensuse

- imagetest/test_suites/metadata/shutdown_script_test.go
- imagetest/test_suites/metadata/startup_script_test.go
> Test that startup and shutdown scripts are not executed on agent reinstallation

- imagetest/test_suites/cvm/setup.go
- imagetest/test_suites/guestagent/setup.go
- imagetest/test_suites/guestagent/windows_password_test.go
- imagetest/test_suites/hotattach/hot_attach_test.go
- imagetest/test_suites/oslogin/oslogin_utils.go
- imagetest/test_suites/oslogin/ssh_test.go
- imagetest/utils/test_utils.go
Tests windows automated password generation, similar to the example: https://cloud.google.com/compute/docs/instances/windows/automate-pw-generation
In this test, it first creates the user, then runs the example code, and finally validates that the new password for the user is correct.
> Windows password test

- concourse/pipelines/linux-image-build.jsonnet
> Build centos-7-predictable-nic

- imagetest/test_suites/metadata/shutdown_script_test.go
- imagetest/test_suites/metadata/startup_script_test.go
> Add aliases for apt reinstall in metadata suite

- imagetest/test_suites/packagevalidation/package_test.go
> Check snap for packages when available

- imagetest/test_suites/guestagent/setup.go
- imagetest/test_suites/guestagent/snapshot_test.go
> Test guest flush snapshots with VSS on windows

- imagetest/test_suites/packagevalidation/package_test.go
This change introduces a generic package rules structure, it supports checking for package names alternatives (different distros may have different namings) and defines rules for skipping a given image (based on a expression matching) and also rules for exact image matching (working in the opposite direction of the skipping rules, it will only apply if the image name expression matches).
> package_test: define a generic package rules structure

- imagetest/test_suites/packagevalidation/package_test.go
> Skip checking for google-cloud-cli on sles and suse

- imagetest/test_suites/security/image_security_test.go
> Add windows support in security suite

- imagetest/test_suites/sql/setup.go
- imagetest/test_suites/windowscontainers/setup.go
> Don't create windowscontainers or sql VMs if the image being tested isn't windows

- imagetest/test_suites/metadata/shutdown_script_test.go
- imagetest/test_suites/metadata/startup_script_test.go
> Retry reinstalling guest-agent on suse when it fails

- imagetest/test_suites/sql/setup.go
> Only run sql suite tests on windows SQL server images

- imagetest/test_suites/storageperf/iops_read_test.go
- imagetest/test_suites/storageperf/iops_write_test.go
- imagetest/test_suites/storageperf/setup.go
- imagetest/test_suites/storageperf/startupscripts/install_fio.ps1
- imagetest/test_suites/storageperf/storage_perf_utils.go
Implement hyperdisk benchmarking instructions, as the doc was recently updated at https://cloud.google.com/compute/docs/disks/benchmark-hyperdisk-performance
> Hyperdisk test case commands

- imagetest/test_suites/guestagent/telemetry_test.go
- imagetest/test_suites/security/image_security_test.go
- imagetest/test_suites/security/setup.go
- imagetest/test_suites/ssh/host_key_test.go
- imagetest/test_suites/ssh/image_ssh_test.go
- imagetest/test_suites/ssh/setup.go
- imagetest/utils/test_utils.go
I added support for both the ssh testing done in the ssh suite and the ssh security options checked in the security suite
/cc @koln67 @jjerger
> Add ssh testing support for windows

- imagetest/test_suites/network/dhcp_test.go
> Check DHCP settings on windows

- imagetest/test_suites/metadata/setup.go
- imagetest/test_suites/metadata/sysprep_test.go
> Test windows-sysprep-specialize

- imagetest/test_suites/security/image_security_test.go
> In windows security tests, add an adminstrator to the test vm and check the ssh config in reference to that user

- imagetest/test_suites/security/image_security_test.go
> Implement TestSockets in windows

- imagetest/test_suites/hotattach/hot_attach_test.go
- imagetest/test_suites/hotattach/setup.go
This isn't actually attaching, but the rest of the test behaves the same which is why I stuck it in this suite.
I reworked the hotattach utility functions slightly to make it a bit more flexible. The disk name is passed to the guest through the MDS now.
NVMe disks surface the disk name through friendlyname so I used that to identify disks when available, falling back to just using disk 1 when not.
/cc @koln67 @elicriffield
> Add LSSD case for hotattach

- container_images/citpresubmit/main.sh
> Run citpresubmit in compute-image-test-pool-001

- imagetest/fixtures.go
- imagetest/test_suites/networkperf/setup.go
Need to be able to set the zone correctly, and set the network region when necessary
Also fixed some typos in architecture strings..
/cc @koln67 @drewhli
> Fix issues with gen 4 networkperf testing

- imagetest/test_suites/storageperf/setup.go
> Specify boot disk type for storageperf test cases

- imagetest/test_suites/packagevalidation/setup.go
- imagetest/test_suites/packagevalidation/windows_version_test.go
> Test Server-Gui-Shell installation state

- imagetest/test_suites/metadata/shutdown_script_test.go
- imagetest/test_suites/metadata/startup_script_test.go
> Fix guest agent package name on windows

- concourse/pipelines/windows-image-build-staging.jsonnet
- concourse/pipelines/windows-image-build-standard.jsonnet
- concourse/pipelines/windows-image-build.jsonnet
- windows 10 22h2
- windows 11 22h2
- windows 11 23h2
- windows 2025 * preview
> Adding additional windows builds

- imagetest/utils/test_utils.go
This append isn't doing anything and gocheck points that out now.
/cc @drewhli @koln67
> Fix gocheck

- imagetest/cmd/wrapper/main.go
- imagetest/test_suites/disk/disk_readwrite_test.go
- imagetest/test_suites/disk/disk_resize_test.go
In order to run CIT against COS, we are proposing the following refactoring for the disk tests.
> Refactoring disk tests to work on COS

- imagetest/test_suites/packagevalidation/gce_sysprep_test.go
> Test that google_osconfig_agent is disabled

- imagetest/test_suites/licensevalidation/setup.go
> Account for rhel-sap-byos and architecture suffixes in licensevalidation

- imagetest/test_suites/network/alias_ip_test.go
- imagetest/test_suites/network/setup.go
Bug filed internally for this.
> Add better support for COS, SLES, and Ubuntu in the network suite.

- concourse/pipelines/linux-image-build.jsonnet
> Run linux image test pipelines in us-central1-b

- imagetest/cmd/manager/main.go
- imagetest/test_suites/winrm/setup.go
- imagetest/test_suites/winrm/winrm_test.go
Tests that a GCE VM can establish a winrm connection to another GCE vm and execute remote powershell commands over it
/cc @koln67 @bkatyl
> Add winrm test suite

- imagetest/test_suites/licensevalidation/setup.go
> Add rhel c3m image support in licensevalidation

- concourse/pipelines/guest-package-build.jsonnet
/cc @a-crate @koln67 @elicriffield @zmarano
> Fix exclude name for licensevalidation

- concourse/pipelines/artifact-releaser-test.jsonnet
Test the push message to artifact registry in autopush, using random string data.
> Artifact Registry basic testing

- imagetest/test_suites/imageboot/live_migrate_test.go
- imagetest/test_suites/imageboot/setup.go
- imagetest/test_suites/imageboot/suspend_resume_test.go
> Add livemigrate and suspend/resume testing to imageboot suite

- concourse/pipelines/guest-package-build.jsonnet
> Fix licensevalidation exclusion

- imagetest/test_suites/imageboot/live_migrate_test.go
- imagetest/test_suites/imageboot/suspend_resume_test.go
> Improve reliability of suspend/resume and livemigrate testing

- imagetest/test_suites/imageboot/live_migrate_test.go
- imagetest/test_suites/imageboot/suspend_resume_test.go
> Mark test start on windows correctly

- imagetest/test_suites/licensevalidation/license_test.go
Doesn't work for MBR images
/cc @jjerger @koln67
> Revert license activation check changes in #1060

- imagetest/test_suites/licensevalidation/setup.go
> Expect google windows-internal licenses for windows bios images

- imagetest/test_suites/imageboot/setup.go
> Fix check for ubuntu 1804 in imageboot

- imagetest/test_suites/imageboot/setup.go
> Test suspend on suse images

- imagetest/test_suites/oslogin/ssh_test.go
Due to the async nature of the test implementation the client side should perform a few attempts to create the ssh client before failing, in the mean time the server could be still in initialization process and the client is failing before we have any change of success - creating test flakiness.
> oslogin: retry for a minute when creating ssh client

- imagetest/cmd/manager/main.go
> Correct parentheses around exit status logic

- imagetest/test_suites/metadata/metadata_utils.go
When installing/upgrading package processes with dnf and yum the package manager will always try to sync the database of all repos, eventually some repos could be unavailable this change introduces a query to determine what repo is installing such a package and do the operation only against that repo by providing --enable-repo=<repo> argument to the update/install/upgrade operations reducing with that the surface of errors by unavailable repositories.
> metadata utils: query repo and use repo for dnf and yum ops

- imagetest/test_suites/metadata/metadata_utils.go
Additionally make sure to also log the error output in case of error for for querying and the install/update package commands.
> metadata: fix repo argument for yum and dnf

- imagetest/test_suites/winrm/winrm_test.go
> Retry winrm client connections until the test times out or the connection succeeds

- imagetest/cmd/manager/main.go
- imagetest/fixtures.go
- imagetest/test_suites/loadbalancer/loadbalancer_test.go
- imagetest/test_suites/loadbalancer/setup.go
/cc @drewhli @koln67 
/hold
Ready for review, just want to verify windows functionality before merge. Not expecting any problems though.
> Test that images can function as L3 and L7 load balancer backends

- imagetest/test_suites/cvm/cvm_test.go
- imagetest/test_suites/cvm/setup.go
> Test SEV live migration

- concourse/pipelines/linux-image-build.jsonnet
remove the redhat c3 metal stuff from concourse
> remove the redhat c3 metal stuff from concourse

- imagetest/test_suites/licensevalidation/license_test.go
- imagetest/test_suites/licensevalidation/setup.go
Also make failure messages clearer.
> Fix windows bios images license test failures

- imagetest/test_suites/metadata/startup_script_test.go
> Skip the agent-reinstall section of startup script test on SUSE

- imagetest/test_suites/network/setup.go
/assign @zmarano 
This will still test multinic and and gvnic functionality separately on EL7 just won't test them together (which is a case we already know is problematic). Should significantly cut down or eliminate flakes on EL7.
> On EL7, use an extra VM to test gvnic instead of the multinic vm

- imagetest/test_suites/ssh/host_key_test.go
- imagetest/test_suites/ssh/image_ssh_test.go
> Fix GetRealVMName call in ssh suite

- concourse/pipelines/windows-image-build-staging.jsonnet
- concourse/pipelines/windows-image-build-standard.jsonnet
- concourse/pipelines/windows-image-build.jsonnet
> Disable CIT in windows piplines

- imagetest/test_suites/network/multinic_minimal_network_test.go
> Rename ping marker file for windows images

- concourse/pipelines/debian-worker-image-build.yaml
* Note not going to convert this to jsonnet right now.
> Add Debian 12 worker builds.

- imagetest/test_suites/metadata/metadata_utils.go
- imagetest/test_suites/metadata/shutdown_script_test.go
- imagetest/test_suites/metadata/startup_script_test.go
> Don't fail metadata tests unless the agent fails to reinstall

- imagetest/test_suites/network/multinic_minimal_network_test.go
This is more reliable on windows. The test results we care about are from the send ping side so false positives are not a concern.
/cc @koln67 @drewhli
> Wait for ping on first boot instead of second

- concourse/pipelines/windows-image-build-staging.jsonnet
- concourse/pipelines/windows-image-build-standard.jsonnet
- concourse/pipelines/windows-image-build.jsonnet
This reverts commit 07b211d530d23d16cf13c23ddd999ef83f8e960b.
/cc @zmarano @bkatyl
> Revert "Disable CIT in windows piplines (#1130)"

- imagetest/test_suites/loadbalancer/loadbalancer_test.go
> Don't accept envoy proxy error messages from load balancer

- concourse/pipelines/linux-image-build.jsonnet
> Start building RHEL 9.4 for SAP.

- imagetest/test_suites/loadbalancer/loadbalancer_test.go
- imagetest/test_suites/security/image_security_test.go
> Fix CIT on SQL Server

- concourse/pipelines/guest-package-build.jsonnet
> Update install_package_cos.wf.json path to the correct path (add /cos)

- imagetest/test_suites/packagevalidation/windows_version_test.go
Fixes sql server CI failures
Passed locally.
/cc @zmarano @koln67 @drewhli
> Wait for services to start on windows

- concourse/pipelines/container-build.jsonnet
> Fix CIT build job

- concourse/pipelines/container-build.jsonnet
> Fix branch name

- concourse/pipelines/windows-image-build.jsonnet
Win11 24h2 preview and sql server 2022 on win2025 preview
> Win11 24h2 preview and sql server 2022 on win2025 preview

- concourse/pipelines/linux-image-build.jsonnet
- concourse/pipelines/windows-image-build.jsonnet
- concourse/tasks/generate-hash.yaml
- concourse/templates/arle.libsonnet
Compute the sha 256 hash in the concourse image build pipeline and pass it in as part of the JSON.
> Compute sha 256 hash

- concourse/pipelines/windows-image-build-mbr.jsonnet
- concourse/pipelines/windows-image-build-staging.jsonnet
- concourse/pipelines/windows-image-build-standard.jsonnet
- concourse/pipelines/windows-image-build.jsonnet
> Make it possible to release windows images with CIT failures

- concourse/pipelines/guest-package-build.jsonnet
Fix some debian apt cases for AR packages
> Small fixes for apt packages

- concourse/pipelines/windows-image-build-mbr.jsonnet
- concourse/pipelines/windows-image-build-standard.jsonnet
- concourse/pipelines/windows-image-build.jsonnet
> Fix default state of runtests in windows-image-build*

- concourse/pipelines/linux-image-build.jsonnet
- concourse/pipelines/windows-image-build.jsonnet
- concourse/tasks/generate-hash.yaml
img.tar.gz is being overriden when computing the hash
> Use start time in Ms as the filename

- concourse/pipelines/linux-image-build.jsonnet
> Add RHEL 8.10 for SAP builds.

- concourse/pipelines/linux-image-build.jsonnet
> Fix shaum typo

- concourse/pipelines/linux-image-build.jsonnet
Pass in the shasum hash variable
> pass in linux hash

- concourse/pipelines/windows-image-build.jsonnet
shasum_destination instead of sha256_txt
> Pass in correct parameter for windows hash

- concourse/pipelines/windows-image-build.jsonnet
> Add step to load shasum in windows publish

- concourse/pipelines/guest-package-build.jsonnet
/cc @zmarano @sejalsharma-google
> Add COS back to the guest-agent release pipeline

- concourse/pipelines/guest-package-build.jsonnet
Updating args for cos-113-lts.
When we can get CIT to pass on this image, then I will create another PR for arm images.
CCing @a-crate, @dorileo, and @zmarano.
> Update args to install_packag_cos.wf.json

- concourse/pipelines/container-build.jsonnet
Reverts GoogleCloudPlatform/guest-test-infra#1216
> Revert "Use kaniko:latest"

- container_images/gointegtest/common.sh
- packagebuild/common.sh
/cc @ChaitanyaKulkarni28 @drewhli
> Bump go sdk version to latest

- concourse/pipelines/linux-image-build.jsonnet
> Make ubuntu accelerator prototype image pipelines

- concourse/pipelines/container-build.jsonnet
Thought you could specify tag in the resource
> Fix repo definition for kaniko

- concourse/pipelines/linux-image-build.jsonnet
- concourse/pipelines/windows-image-build-mbr.jsonnet
- concourse/pipelines/windows-image-build-staging.jsonnet
- concourse/pipelines/windows-image-build-standard.jsonnet
- concourse/pipelines/windows-image-build.jsonnet
Include windows-image-build-{mbr,staging,standard} in windows pipeline changes
/cc @bkatyl @koln67
> Filter for exact suite names

- concourse/pipelines/debian-worker-image-build.yaml
> Don't redefine resource_types

- concourse/pipelines/guest-package-build.jsonnet
Use debian-12-arm64 worker instead of debian-11-arm64 worker
/hold
/cc @ChaitanyaKulkarni28 @dorileo @drewhli
> Build guest-agent for debian 12 ARM and update worker.

- concourse/pipelines/linux-image-build.jsonnet
> Add rocky to accelerator pipeline

- concourse/pipelines/guest-package-build.jsonnet
- concourse/pipelines/linux-image-build.jsonnet
- concourse/pipelines/windows-image-build.jsonnet
Temporarily disabling to allow builds to continue while AR pulls are investigated
> Comment out metrics reporting from image and package build

- container_images/gobuild/Dockerfile
- container_images/gocheck/Dockerfile
- container_images/gotest/Dockerfile
This reverts commit fff1c8300fa552c9bc1e3097e7bba080e67247e7.
> Revert "update go containers to also install protobuffer tools. (#1248)"

- concourse/pipelines/linux-image-build.jsonnet
Testing on every image build will be flaky due to frequent use of test users.
/cc @drewhli @lpleahy
> Test oslogin concourse

- packagebuild/workflows/build_deb11.wf.json
- packagebuild/workflows/build_deb11_arm64.wf.json
- packagebuild/workflows/build_deb12.wf.json
- packagebuild/workflows/build_deb12_arm64.wf.json
- packagebuild/workflows/build_el6.wf.json
- packagebuild/workflows/build_el8.wf.json
- packagebuild/workflows/build_el8_arm64.wf.json
- packagebuild/workflows/build_el9.wf.json
- packagebuild/workflows/build_el9_arm64.wf.json
- packagebuild/workflows/build_goo.wf.json
- packagebuild/workflows/build_package.wf.json
Pass in the extra git ref used to build legacy guest agent and plugin manager side-by-side.
> package build: pass in extra git ref

- concourse/pipelines/guest-package-build.jsonnet
With this change we add a new trigger to the guest-agent-dev build pipeline watching the new guest-agent repository (the main branch) and adds the required bits to pass down the discovered commit's hash to the daisy workflow.
> package build: add extra source to guest-agent build pipeline

- concourse/pipelines/guest-package-build.jsonnet
Fix architecture selection for guest-agent. Fix guest_configs image references, make buildid package specific.
> Fix guest environment build pipeline failures

- packagebuild/daisy_startupscript_deb.sh
> Modify debian startupscripts to utilize extra_repo if it exists

- packagebuild/daisy_startupscript_deb.sh
> Install protoc go extensions

- concourse/pipelines/guest-package-build.jsonnet
/cc @dorileo @ChaitanyaKulkarni28 
Fix rocky 8 dest_image and worker_image, fix rocky 9 arm dest_image.
> Fix more typos in build_guest_configs

- concourse/pipelines/guest-package-build.jsonnet
Removing workaround to AR access issue; no longer needed
> Re-enable metrics for package builds

- concourse/pipelines/guest-package-build.jsonnet
Not sure about where this whole diff thing came from, but the line of interest is line 853.
> Add extra_repo to guest-agent-dev pipeline

- concourse/pipelines/linux-image-build.jsonnet
Testing a different approach to allow per-OS filtering, but keep a default if it is not defined.
> Test passing in cit suite filter as a list with override

- concourse/pipelines/linux-image-build.jsonnet
> Fix old reference to citsuite

- concourse/pipelines/linux-image-build.jsonnet
> Add arm64 variants for CentOS Stream 9, RHEL 8, and AlmaLinux 9

- concourse/pipelines/linux-image-build.jsonnet
Allows for easier pipeline definitions in terms of defining additional tests
> Update cit filtering to use append instead of replace method

- concourse/pipelines/windows-image-build-staging.jsonnet
We may not need to fork this anymore
> Test using default registry-image resource

- concourse/pipelines/guest-package-build.jsonnet
> Add NIC naming tests and package manager tests to guest-configs release pipeline

- concourse/pipelines/linux-image-build.jsonnet
This reverts commit 3d91c1a84e4b14120eda630d54a9f787cdb1671d.
> revert "Test OSLogin on images before publishing (#1250)"

- concourse/pipelines/windows-image-build-staging.jsonnet
This should use the public concourse registry image instead of the forked one.
> Add metrics to windows staging pipeline using public registry image resource

- concourse/pipelines/linux-image-build-dev.jsonnet
- concourse/pipelines/pipeline-set-pipeline.yaml
Holding until we're ready to submit
> Fork Linux build pipeline for development purposes

- concourse/pipelines/linux-image-build.jsonnet
> Fix Rocky Accelerator publish gsc_dir

- concourse/pipelines/linux-image-build.jsonnet
Dropped for conciseness, but did not remove from the iso locations
> Drop "-with" prefix from remaining accelerator image names

- concourse/pipelines/linux-image-build-dev.jsonnet
Moving some images around; updating regex workflow
> Sync Dev pipeline to reflect current prod pipelines

- concourse/pipelines/linux-image-build-dev.jsonnet
> Switch accelerator gcs-dir to rocky-linux in linux-image-build-dev

- concourse/pipelines/linux-image-build-dev.jsonnet
- concourse/pipelines/linux-image-build.jsonnet
> Allow extra, custom test tasks in image build pipelines

- container_images/registry-image-forked/check_test.go
- container_images/registry-image-forked/commands/check.go
- container_images/registry-image-forked/go.mod
- container_images/registry-image-forked/in_test.go
- container_images/registry-image-forked/out_test.go
- container_images/registry-image-forked/types.go
Newer version to support AR authentication; old version was not authenticating.
> Update go-containerregistry version

- container_images/registry-image-forked/go.sum
Reflects new go-containerregistry version
> Update go-containerregistry sum

- concourse/pipelines/linux-image-build-dev.jsonnet
> Run accelerator tests on the accelerator images in -dev

- OWNERS
> Cleanup owners file.

- concourse/pipelines/linux-image-build.jsonnet
Now that the accelerator type parameter is part of the test suite, pass it in.
> Pass in the acceleratortype

- concourse/pipelines/linux-image-build-dev.jsonnet
- concourse/pipelines/linux-image-build.jsonnet
This was updated last week; updating test definitions in pipeline
> Update reservation name for A3 tests

- concourse/pipelines/accelerator-image-build.jsonnet
First attempt at splitting this out
> Fork accelerator build into its own pipeline

- concourse/pipelines/accelerator-image-build.jsonnet
- concourse/pipelines/pipeline-set-pipeline.yaml
> Add accelerator pipeline to official pipelines

- concourse/pipelines/linux-image-build-dev.jsonnet
- concourse/pipelines/linux-image-build.jsonnet
> Remove accelerator builds from generic Linux pipelines

- concourse/pipelines/accelerator-image-build.jsonnet
Enables building of 570 images and A4 build/testing
> Add necessary changes for building A4 with Concourse

- concourse/pipelines/guest-package-build.jsonnet
- packagebuild/workflows/build_deb11_arm64.wf.json
- packagebuild/workflows/build_deb12_arm64.wf.json
- packagebuild/workflows/build_el10_arm64.wf.json
- packagebuild/workflows/build_el8_arm64.wf.json
- packagebuild/workflows/build_el9_arm64.wf.json
- **fix typo in images list for rhel-10**
- **t2a -> c4a for arm builds**
> t2a -> c4a for arm builds

- concourse/pipelines/guest-package-build.jsonnet
- packagebuild/workflows/build_deb13.wf.json
Adds some of the base packages for Debian 13
> Update guest package build pipeline for Debian 13

- concourse/pipelines/guest-package-build.jsonnet
Missed a reference to bookworm --> trixie
> Update repo reference in package upload

- concourse/pipelines/accelerator-image-build.jsonnet
Stagger with 90 minutes instead of 60
> Update accelerator-image-build.jsonnet to stagger with 90 minutes

- concourse/pipelines/linux-image-build-dev.jsonnet
- concourse/templates/common.libsonnet
Re-shuffling old PR into the new pipeline
> Add Debian-13 to dev build pipeline

- concourse/pipelines/guest-package-dev-build.jsonnet
Updated derivative image build sections but forgot to add it to package builds
> Update package builds with debian13-arm

- concourse/pipelines/guest-package-dev-build.jsonnet
> Fix typo in one of the build defs

- concourse/pipelines/guest-package-dev-build.jsonnet
Missed a reference to deb12 here
> Update package path in oslogin build

- concourse/pipelines/guest-package-build.jsonnet
> Add centos-stream-9 to guest-agent package build/test pipeline

- concourse/pipelines/accelerator-image-build.jsonnet
Reverts GoogleCloudPlatform/guest-test-infra#1418
> Revert "Temporarily disable a3u CIT tests in image build"

- concourse/pipelines/guest-package-build.jsonnet
> Add windows image build task, not adding to list of images to test yet.

- concourse/pipelines/guest-package-build.jsonnet
> User correct worker image and machine type for ubuntu arm images

- concourse/pipelines/guest-package-build.jsonnet
> Add sles-15 to image derivation

- concourse/pipelines/guest-package-build.jsonnet
- Make list of images being tested readable
- Add rhel-sap to the build pipeline
- Add sles, windows and ubuntu derived images to list of images to be tested
> Add all built images to test list

- concourse/pipelines/guest-package-build.jsonnet
- concourse/pipelines/guest-package-dev-build.jsonnet
Most of the diff is from some auto-formatting of the oslogin jobs, it seems.
> Update pipelines to use new guest package builder project.

- concourse/pipelines/guest-package-build.jsonnet
> Put OSLogin CIT tests in oslogin-cit project

- concourse/pipelines/guest-package-build.jsonnet
> Fix T2A supported zones

- concourse/pipelines/guest-package-build.jsonnet
> Use other zones before central1-a to avoid resource exhaustion

- concourse/pipelines/guest-package-build.jsonnet
> Add nicsetup test suite to test pipeline

- concourse/pipelines/guest-package-build.jsonnet
> Split windows test and run on different machine type to improve test/build times

- concourse/pipelines/guest-package-build.jsonnet
> Split partner images to run in parallel, add oslogin tests

- concourse/pipelines/guest-package-build.jsonnet
> Add all remaining rhel-sap-ha images

- concourse/pipelines/guest-package-build.jsonnet
> Add ubuntu 1604 and all sles sp images to test list

- concourse/pipelines/guest-package-build.jsonnet
> Add sysprep pacakge to the image build

- concourse/pipelines/guest-package-build.jsonnet
> Tests are extremely flaky on Rhel 8-6 remove it from the list

- packagebuild/daisy_startupscript_deb.sh
Allows for us to build multiple binaries using the same source repo
> Support multiple binaries from single source package

- concourse/pipelines/guest-package-dev-build.jsonnet
Testing building the package with concourse prior to release
> Add package upload workflow for new config package

- concourse/pipelines/guest-package-build.jsonnet
> Add rhel-10-byos images

- concourse/pipelines/guest-package-build.jsonnet
> Use right project for rhel-10-byos image

- concourse/pipelines/windows-image-build.jsonnet
Add Windows 11 25h2 and remove EOL versions
> Add Windows 11 25h2

- concourse/pipelines/guest-package-build.jsonnet
Also disable triggers for guest agent stable and dev pipelines.
/hold
> Add trigger field to package build job to customize whether it triggers off of commits

- concourse/pipelines/guest-package-build.jsonnet
Reverts GoogleCloudPlatform/guest-test-infra#1521 concourse pipeline is broken since this change
> Revert "Add trigger field to package build job to customize whether it triggers off of commits"
