container_images/gotest/main.sh
without this; go test is failing for presubmits
https://prow.gflocks.com/view/gcs/oss-prow/pr-logs/pull/GoogleCloudPlatform_guest-test-infra/7/infra-presubmit-gotest/1182113108668190720
=> allow go test for multiple main pkgs

container_images/gotest/main.sh
without `-v`, go test doesn't produce enough output for go-junit-report to work with. so our prow interface isn't showing us a test breakdown.
=> verbose gotest

container_images/daisy-builder/main.sh
some of the tagging workflow is failing. added this log line to get more helpful debug logs
example failure
https://prow.gflocks.com/view/gcs/oss-prow/logs/osconfig-build/1197953476190015488
=> add debug lines

packagebuild/daisy_startupscript_rpm.sh
without this the builds are getting aborted
sample failure log
Dec 27 23:24:02 inst-build-deb-build-packages-el8-build-package-gz6j2 startup-script[2671]: INFO startup-script-url: Upgrade  4 Packages
Dec 27 23:24:02 inst-build-deb-build-packages-el8-build-package-gz6j2 startup-script[2671]: INFO startup-script-url: Total download size: 5.5 M
Dec 27 23:24:02 inst-build-deb-build-packages-el8-build-package-gz6j2 startup-script[2671]: INFO startup-script-url: Is this ok [y/N]: Operation aborted.
full build log link
https://00e9e64bac9601d40f93e16f022d16fa8118a6f49607d4ba2b-apidata.googleusercontent.com/download/storage/v1/b/gcp-guest-daisy-bkt/o/daisy-build-packages-20191227-23:21:33-brdh2%2Fdaisy-build-package-20191227-23:21:34-gz6j2%2Flogs%2Finst-build-deb-build-packages-el8-build-package-g …
=> Fix el8 package builds

container_images/daisy-builder/main.sh, packagebuild/daisy_startupscript_deb.sh, packagebuild/daisy_startupscript_goo.sh, packagebuild/daisy_startupscript_rpm.sh
the absence of trailing slash means that for uploads with one file, we are uploading it as the 'dir'. eg. uploading my_package.rpm to gs://bucket/daisy-outs instead of gs://bucket/daisy-outs/my_package.rpm
=> Correct upload paths, log paths

container_images/gobuild/main.sh, container_images/gocheck/main.sh, container_images/gotest/main.sh
Support an optional directory argument, which allows these tools to be run against repos containing multiple go modules.
=> Optional directory argument for gobuild,gotest,gocheck images

packagebuild/common.sh, packagebuild/daisy_startupscript_deb.sh, packagebuild/daisy_startupscript_rpm.sh
* Inject source control tags into debian control and RPM spec
* Don't assume pull ref is a branch, instead check out object into working tree using FETCH_HEAD ref (enables checkout of tags)
* Skip unversioned specs if versioned specs exist
=> Store git commit, support checkout of tags

packagebuild/common.sh
Chose to not move to 1.14 as I am not positive all builders are updated to 1.14 yet, and 1.13 was the min needed to unblock guest agent builds
=> Update builds to use go 1.13.9

container_images/gotest/Dockerfile, container_images/gotest/main.sh
it seems failing tests won't show up in junit format because we had `set -e` in this container. or possibly go test used to return code 0 even with failing tests, i'm not sure.
=> gotest: remove set -e

container_images/cloudbuild.yaml
Allow the build to continue as #35 is in progress.
Testing:
Ran `gcloud builds submit --substitutions COMMIT_SHA=1234556 --config container_images/cloudbuild.yaml` from master.
=> Remove selinux-tools from build

container_images/pytest/.dockerignore, container_images/pytest/Dockerfile, container_images/pytest/README.md, container_images/pytest/example/.gitignore, container_images/pytest/example/README.md, container_images/pytest/example/run.sh, container_images/pytest/example/src/application/main.py, container_images/pytest/example/src/application/main_test.py, container_images/pytest/example/src/application/pyproject.toml, container_images/pytest/example/src/application/setup.py, container_images/pytest/example/src/sums/ints.py, container_images/pytest/example/src/sums/setup.py, container_images/pytest/main.py
Prior to this, the package being tested could only have dependencies on pypi packages. This PR enables dependencies on Python packages from the repo being tested.
See the new `example` directory for tests that run against an application package, where the application package depends on a library package.
=> pytest: allow in-repo dependencies

container_images/gointegtest/integ-test-all.wf.json
Removing CentOS6 and RHEL6 from integration tests
=> Removing CentOS6 and RHEL6 from integration tests

concourse/pipeline/pipeline-set-pipeline.yaml
this will automate changes to the linux-image-build pipeline based on git commits
after merge, we will create this pipeline manually via `fly set-pipeline -p set-pipeline -c pipelines/pipeline-set-pipeline.yaml`
following this, new changes to linux-image-build.yaml will be applied automatically
new pipelines we want to automate may be added by updating this file and running set-pipeline again
later, we can add `set_pipeline: self` to this file to fully automate the process
=> add pipeline-set-pipeline

concourse/pipelines/dev-image-build.yaml
we have to add environment var as it's required in concourse task config, even it's not in publish workflow
=> fix typo and fix missing var bug

concourse/pipelines/guest-package-build.yaml
rollback until package builder is fixed, as this blocks the builder
=> rollback #82

concourse/pipelines/guest-package-build.yaml, concourse/pipelines/linux-image-build.yaml, concourse/pipelines/pipeline-set-pipeline.yaml
we must not separate logical pipelines for convenience or aesthetic reasons, as they have implications in the management of the pipeline. to achieve logical separation we can use the grouping feature
=> Rollback 87

container_images/cloudbuild.yaml, container_images/fly-validate-pipelines/Dockerfile, container_images/fly-validate-pipelines/main.sh
build a container image for running `fly validate-pipeline` recursively
shame, it seems there is no `fly validate-task` equivalent
=> add fly-validate-pipelines image

test_manager/test_utils/test_utils.go, test_manager/test_wrapper/test_wrapper.go, test_manager/utils/test_utils.go
* use tempdir for working directory
* add start and finish log lines for daisy
* upload result to daisy-outs rather than parsing test binary path
* don't fatal if tests failed, upload result anyway
* move metadata function to `utils` package
=> test wrapper fixes

container_images/cloud-image-tests/Dockerfile, container_images/cloud-image-tests/build.sh
depends on #98 
depends on #100
rename entries to match new cloud image test layout.
=> update cloud-image-tests container

imagetest/Dockerfile
Step 11/14 : RUN for suite in ./imagetest/test_suites/*; do   cd $suite; go test -c; mv *.test /out; cd ..;   done
---> Running in e3eb756765e3
/bin/sh: cd: line 1: can't cd to ./imagetest/test_suites/image_validation: No such file or directory
no Go files in /build/imagetest/test_suites
mv: can't rename '*.test': No such file or directory
Removing intermediate container e3eb756765e3
---> e447fabbf6b0
Step 12/14 : FROM alpine:edge
---> b0da5d0678e7
Step 13/14 : COPY --from=builder /out/* /
---> Using cache
=> fix folder path in docker

concourse/pipelines/partner-image-export.yaml, concourse/pipelines/pipeline-set-pipeline.yaml, concourse/tasks/daisy-export-images-partner.yaml
These workflows simply export a set of partner images to GCS and then publish some of those images to a staging project used for OS Login staging tests.
=> Partner images export pipelines.

imagetest/cmd/manager/main.go, imagetest/test_suites/network/mtu_test.go, imagetest/test_suites/network/setup.go
➜  manager git:(image-test-mtu) /out/manager -project hanga-testing -zone us-west1-c -images projects/debian-cloud/global/images/debian-10-buster-v20210316
2021/04/23 23:22:09 imagetest: Done with setup
runTestWorkflow: running image_validation on debian-10-buster-v20210316 (ID vnzzl)
runTestWorkflow: running image_boot on debian-10-buster-v20210316 (ID m1bd9)
runTestWorkflow: running network on debian-10-buster-v20210316 (ID pxn2g)
```
<testsuites name="" errors="0" failures="0" tests="0" time="0">
<testsuite name="network-debian-10-buster-v20210316" tests="1" failures="0" errors="0" disabled="0" skipped="0" time="0">
<testcase classname="" name="TestDefaultMTU" time="0"></testcase>
</testsuite>
<testsuite name="image_validation-debian-10-buster-v20210316" tests="4" failures="0" …
```
=> Image test mtu

imagetest/test_suites/image_validation/package_test.go, imagetest/test_suites/image_validation/setup.go
```
<testsuites name="" errors="0" failures="0" tests="0" time="0">
<testsuite name="image_validation-debian-9" tests="1" failures="0" errors="0" disabled="0" skipped="0" time="0">
<testcase classname="" name="TestStandardPrograms" time="7.05"></testcase>
</testsuite>
</testsuites>
<testsuites name="" errors="0" failures="0" tests="0" time="0">
<testsuite name="image_validation-rhel-7" tests="1" failures="0" errors="0" disabled="0" skipped="0" time="0">
<testcase classname="" name="TestStandardPrograms" time="5.21"></testcase>
</testsuite>
</testsuites>
<testsuites name="" errors="0" failures="0" tests="0" time="0">
<testsuite name="image_validation-centos-7" tests="1" failures="0" errors="0" disabled="0" skipped="0" time="0">
<testcase classname="" name="TestStandardPrograms" …
```
=> add test gcloud gsutil

imagetest/test_suites/image_validation/license_test.go
Compare the text using whitespace regex and replaceString
LICNESE:
```
This data is licenced under 2 different licenses
1) GNU General Public License, version 2 or later
2) XFree86 1.0 license
This data can be used freely under either license.
```
```
This data is licenced under 2 different licenses 1) GNU General Public License, version 2 or later 2) XFree86 1.0 license This data can be used freely under either license.
```
```
This data is licenced under 2 different licenses  1) GNU General Public License, version 2 or later 2) XFree86 1.0 license  This data can be used freely under either license.
```
=> use regex \s

imagetest/README.md, imagetest/test_suites/image_validation/license_test.go
* check all glob paths on all systems
* change all instances of `regexp.Regexp.MustCompile` to `regexp.Regexp.Compile`
* add new license string for libselinux package on cent8
* correct copyright=>copyrightPathGlob error in some strings
=> Fix license test

concourse/pipelines/guest-package-build.yaml, concourse/tasks/daisy-build-package-image.yaml
this PR updates the guest-agent build in the guest-package-build-pipeline as follows:
1. build the agent packages
2. build derivative images containing the newly built packages
3. run the image tests against them
4. inject packages to unstable repos
=> Guest agent image tests

concourse/pipelines/guest-package-build.yaml
merge guest-agent integration tests into the `build-guest-agent` job.
the principle for whether an action should be captured in a distinct `job` is largely whether or not we would want to run that job independently of others. in the case of guest-agent integration tests, we always want to run them as a prerequisite to building packages of this version, and never independently. therefore, merge these steps into the build-package job just as unit tests are already included.
=> merge agent integ test

concourse/pipelines/guest-package-build.yaml
the repo definitions have been changed to use per-release prefixes rather than per-release tags. this PR updates the pipeline to match.
=> per release repos for guest agent

concourse/pipelines/windows-image-build.yaml, concourse/tasks/generate-build-ids-windows.yaml
- Added tasks/generate-build-ids-windows.yaml which will generate 2 variables
- Updating gcs file renames to include -v, to distinguish between the normal and internal files.
=> Adding a second build-id variable for internal builds

imagetest/cmd/manager/main.go, imagetest/test_suites/image_validation/image_validation_test.go
```		
<testcase classname="" name="TestFQDN" time="0.04">
<failure type="">    image_validation_test.go:75: hostname does not match metadata. Expected: &#34;vm1-image-validation-5615n.c.gcp-guest.internal&#34; got: &#34;&#34;</failure>
<testsuite name="image_boot-debian-11-bullseye-v20210628" tests="1" failures="0" errors="1" disabled="0" skipped="0" time="0">
<system-err>step &#34;wait-vm2&#34; did not complete within the specified timeout of 30m0s</system-err>
</testsuite>
```
=> fix rhel 7.4 sap

imagetest/test_suites/image_boot/image_boot_test.go
Note that Rocky Linux will support secure boot soon - just not yet.
=> Skip secure boot test on Rocky Linux which doesn't yet support it.

concourse/pipelines/guest-package-build.yaml
we should eventually wire in the image validation tests for this package, but since they're not ready we can do that later on. for now, just add promote-to-{staging,stable} jobs for this package.
=> add promotions for gce package

imagetest/cmd/wrapper/main.go, imagetest/test_suites/image_boot/setup.go
Until Rocky Linux supports secure boot, the second VM fails to boot and the test just times out.
```
BdsDxe: failed to load Boot0001 "UEFI Google PersistentDisk " from PciRoot(0x0)/Pci(0x3,0x0)/Scsi(0x1,0x0): Security Violation
```
=> Fix test flakes for Debian and Rocky Linux

go.mod, imagetest/fixtures.go, imagetest/fixtures_test.go, imagetest/test_suites/disk/setup.go, imagetest/test_suites/network/setup.go, imagetest/testworkflow.go, imagetest/testworkflow_test.go
* move all new network fixtures to fixtures.go
* maintain a convenience pointer in fixture structs
* use convenience pointer instead of name matching loops
* require fixture structs in SetCustomNetwork, reducing necessary safety checks
* add tests for new network fixtures
=> CIT fixups

imagetest/test_suites/security/image_security_test.go
Rewrite the legacy listening socket test 
* Replace `netstat` from net-utils with `ss` utility from iproute2
* Use field separators instead of regular expressions
* Fail test if format from `ss` command doesn't match expectation
=> CIT: listening socket test

concourse/pipelines/linux-image-build.yaml
add a new git resource specific to the imagetest directory and which only produces new versions for changed go files in that directory. configure the image build job to trigger on all new changes.
=> build imagetest container on commit

imagetest/test_suites/ssh/setup.go
ssh test relies on guest-agent picking up the ssh key and creating a user. guest-agent won't touch metadata ssh keys if oslogin is enabled, so verify oslogin is disabled on target vm during test.
=> disable oslogin in ssh test

concourse/pipelines/linux-image-build.yaml
* paths parameter takes globs, not regex
* build-container-image task assumes input is named guest-test-infra, add mappings
=> update trigger for imagetest

imagetest/cmd/manager/main.go, imagetest/testworkflow.go
* add gcs_path parameter
* only auto-detect daisy bucket if gcs_path not set
* move bucket handling to finalize
this change enables user to pass in desired gcs_path which is working directory for the daisy workflows. this also fixes -print and -validate, by populating gcs bucket in the common path in the finalize function.
Test with invalid GCS path:
```
$ docker run cloud-image-tests:latest -project liamh-testing -zone us-west1-b -images debian-10 -filter 'ssh|image_validation' -validate -gcs_path=fake
2021/08/06 00:39:36 imagetest: Done with setup
2021/08/06 00:39:36 Validating test image_validation on image debian-10
2021/08/06 00:39:36 Validate failed: error populating workflow: "fake/2021-08-06T00:39:36Z/image_validation/debian-10" is not a valid GCS path
```
Test with nonexistent …
=> add gcs_path parameter

imagetest/cmd/manager/main.go, imagetest/testworkflow.go
Add log statements for how the manager was invoked, to aid in troubleshooting. Also log the final gcs path, and correct a bug with repeated / separators in gcs paths.
Output as of this PR:
```
$ docker run cloud-image-tests -project liamh-testing -zone us-west1-a -images debian-10 -filter image_boot 
2021/08/06 20:32:30 Running in project liamh-testing zone us-west1-a
2021/08/06 20:32:30 using -filter image_boot
2021/08/06 20:32:30 Add test workflow for test image_boot on image projects/debian-cloud/global/images/family/debian-10
2021/08/06 20:32:30 imagetest: Done with setup
2021/08/06 20:32:31 Storing artifacts and logs in gs://liamh-testing-cloud-test-outputs/2021-08-06T20:32:31Z
2021/08/06 20:32:31 runTestWorkflow: running image_boot on debian-10 (ID 3lvs8)
```
=> add logging for config

imagetest/test_suites/image_boot/setup.go
t.Skip will cause the entire test suite to be skipped. since we don't want to run one of the tests, just don't set up that test in this case.
=> skip secure boot on d9 and rocky linux

imagetest/Dockerfile
test suites can fail to compile but not fail the docker build because this run command will always exit with the status from `cd ..`. this change simply makes a compilation failure into a Docker build failure.
we also need an improvement to presubmits in this repo for test suites, to catch compilation errors.
=> fail on test compilation failure

imagetest/test_suites/image_boot/setup.go
This test is reporting duplicate results. The `go test -run` parameter accepts /-separated *regular expressions* to match the components of the test name. Because of this, `go test -run TestGuestReboot` will run the test TestGuestReboot as well as TestGuestRebootOnHost. Add EOL anchor to prevent this overmatching.
Output after this change:
```
<testsuites name="" errors="0" failures="0" disabled="0" skipped="0" tests="6" time="0">
<testsuite name="image_boot-debian-10" tests="6" failures="0" errors="0" disabled="0" skipped="0" time="0">
<testcase classname="" name="TestGuestBoot" time="0"></testcase>
<testcase classname="" name="TestGuestReboot" time="0"></testcase>
<testcase classname="" name="TestGuestShutdownScript" time="0"></testcase>
<testcase classname="" …
```
=> fix image_boot test

imagetest/Dockerfile, imagetest/junit.go, imagetest/junit_test.go, imagetest/testworkflow.go
Currently CIT emits a per-test-*suite* error status when the entire test suite failed. This is not well handled by our existing jUnit-aware tools (testgrid and spyglass), so switch to emitting per-test-case errors. This is accomplished by generating a list of known tests per suite at build time, and reading the file during workflow result parsing. 
Test workflow failure today:
```
<testsuites name="" errors="1" failures="0" disabled="0" skipped="0" tests="1" time="0">
<testsuite name="ssh-debian-10" tests="1" failures="0" errors="1" disabled="0" skipped="0" time="0">
<system-err>error validating workflow: must provide workflow field &#39;Project&#39;</system-err>
</testsuite>
</testsuites>
```
Test output after this PR:
```
<testsuites name="" errors="0" failures="4" disabled="0" …
```
=> CIT: Emit per-testcase errors on workflow failure

imagetest/cmd/wrapper/main.go
i don't really understand what the addition of the sleep was intended to accomplish. but hijacking that closure to repeatedly emit the FINISHED-TEST signal which is sometimes missed by Daisy, leading to test workflow timeouts (especially in reboot-based tests and especially on centos-8)
=> emit finish signal to console multiple times

imagetest/cmd/manager/main.go, imagetest/fixtures.go, imagetest/testworkflow.go
* enable providing multiple test projects to stripe tests across via `-test_projects` flag
* enable tests to declare a write lock on a project via `t.LockProject()` fixture
* (minor) improve error message from ssh-key fixture
=> add project pools and locking

concourse/tasks/generate-timestamp.yaml
TL;DR - busybox's date command doesn't support the '%N' nanoseconds option. This PR updates the generate-timestamp concourse task to use bash instead.
Tested (with a run on the cluster this time):
```
initializing
selected worker: concourse-worker-0
running /usr/local/bin/bash -c timestamp=$((${EPOCHREALTIME/./}/1000)); echo $(($timestamp/1000)) | tee timestamp/timestamp; echo $timestamp | tee timestamp/timestamp-ms
1630529100
1630529100797
```
=> Fix generate timestamp by using bash image instead of busybox's date

concourse/pipelines/guest-package-build.yaml, concourse/tasks/image-test-args.yaml
Add a filter to skip the network tests during package builds until we complete project migration for network tests
=> skip network test in package testing

concourse/tasks/generate-package-version.yaml
existing logic is incorrectly producing e.g. `20210913.1` instead of `20210913.01`. fix with printf instead of echo
=> fix package generation task

container_images/gocheck/Dockerfile
Latest go image in Docker registry has changes that are incompatible with our version of go. See failing presubmit on GoogleCloudPlatform/guest-agent#133
=> lock go version

concourse/pipelines/dev-image-build.yaml, concourse/tasks/publish-job-result.yaml
```
fly validate-pipeline --config concourse/pipelines/dev-image-build.yaml 
looks good
```
Tested that the same success/failure handlers work in my dev pipeline in Concourse.
The config lines are a bit repetitive; looked to see if there is a way to reduce clutter by referencing vars available in the pipeline overall (rather than directly re-specifying the same ones each time). Turned up "Parameterizing a task file with vars" [here](https://concourse-ci.org/jobs.html#schema.step.task-step.vars) which will check in with a credential manager to try and resolve implicit vars. The only thing I found to make this less explicit was a 'dummy' var source (which lets you specify static values at the top of a pipeline). That would at least let us reduce the duplicated entries which are the same …
=> Instrument the dev-image-build pipeline with success/failure/duration metrics

container_images/gointegtest/run_integ_tests.sh
Use curl instead of git for checking out code under test. This removes all package management from the process, increasing reliability.
=> use curl in gointegtest

concourse/pipelines/artifact-releaser-autopush.yaml, concourse/pipelines/windows-image-build.yaml
This is one part of the overall image pipeline cutover. This PR focuses on Windows image build changes.
Hold until ready to cutover.
/hold
=> Cutover image pipeline - Windows image build

concourse/pipelines/guest-package-build.yaml, concourse/pipelines/linux-image-build.yaml
* use commit sha when building guest agent package
* use correct parameter name for gcloud-publish-image task
=> fix package and image params

concourse/pipelines/guest-package-build.yaml
this one is more specific than the general case so it's taking precedence. disable here also
=> disable oslogin

container_images/gotest/main.sh
This updates `gotest` so that arguments after the test directory are passed to `go test`. The current motivation: Allow the tests we're onboarding to tune parallelism and timeout.
```
docker run -e ARTIFACTS=/tmp/artifacts -v /tmp/artifacts:/tmp/artifacts \
-v ~/daisy:/daisy gotest /daisy/cli_tools/common/assert/ -test.parallel=30 -test.timeout=5s
+ BUILD_DIR=/daisy/cli_tools/common/assert/
+ [[ -n /daisy/cli_tools/common/assert/ ]]
+ cd /daisy/cli_tools/common/assert/
+ shift
+ echo 'Pulling Linux imports...'
Pulling Linux imports...
+ go get -d -t ./...
go: downloading github.com/stretchr/testify v1.6.1
go: downloading gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
+ echo 'Pulling …
```
=> gotest: Allow clients to specify extra test args.

concourse/tasks/daisy-build-images.yaml
the daisy container has a copy of the workflows from compute-image-tools, which are used for the references within the build-publish workflows. this PR changes the reference so we are always consistently using the git resource from the pipeline
=> use git resource rather than container wf

concourse/tasks/daisy-build-images.yaml
this variable is interpreted by daisy as relative to the directory with the workflow, so it needs to do parent relative directories to get back to the compute-image-tools/daisy_workflows root
there are unfortunately no quick variables to get you back to the root of a concourse task.
=> use relative parent path for workflow_root

concourse/tasks/daisy-build-images.yaml
third time is the charm. it's just 2 directories up: out of family-specific directory, and out of build-publish directory.
=> use correct relative path

concourse/pipelines/windows-image-build.yaml
See #238 for context; applying the same instrumentation to each pipeline. This PR is for the windows-image-build pipeline.
=> Instrument the windows-image-build pipeline with job metrics

concourse/pipelines/partner-image-export.yaml
See #238 for context; applying the same instrumentation to each pipeline. This PR is for the partner-image-export pipeline.
=> Instrument the partner-image-export pipeline with job metrics

concourse/pipelines/container-build.yaml
I used the `gotest` stanza as an example.
Tested locally:
```
docker run --volume /home/ericedens/git/guest-test-infra:/guest-test-infra:ro \
gcr.io/kaniko-project/executor \
--dockerfile=Dockerfile \
--context /guest-test-infra/container_images/cli-tools-module-tests \
--no-push
```
.. . truncated output ...
```
Fetched 11.5 MB in 0s (43.5 MB/s)
Selecting previously unselected package libfuse2:amd64.
(Reading database ... 15559 files and directories currently installed.)
Preparing to unpack .../libfuse2_2.9.9-1+deb10u1_amd64.deb ...
Unpacking libfuse2:amd64 (2.9.9-1+deb10u1) ...
Selecting previously unselected package fuse.
Preparing to unpack .../fuse_2.9.9-1+deb10u1_amd64.deb ...
Unpacking fuse (2.9.9-1+deb10u1) ...
Selecting previously unselected package gcsfuse.
Preparing to unpack …
```
=> Concourse build for cli-tools-module-tests

concourse/pipelines/guest-package-build.yaml, concourse/tasks/gotest.yaml, concourse/tasks/publish-coverage.yaml, container_images/concourse-metrics/Dockerfile, container_images/concourse-metrics/cmd/publish-coverage/main.go, container_images/concourse-metrics/pkg/requests/requests.go, container_images/gotest/main.sh
* add new `publish-coverage` binary to the `concourse-metrics` container
* add gotest Concourse Task which invokes the gotest container originally written for prow
* add steps to `build-guest-agent` Concourse Job to produce and later publish coverage metrics
=> add line coverage for guest agent

container_images/fly-validate-pipelines/main.sh, container_images/jsonnet-go/Dockerfile
`gcr.io/gcp-guest/jsonnet-go`: contains the jsonnet binary built from go source. contains a shell
`gcr.io/gcp-guest/fly-validate-pipelines`: update to include and use jsonnet for template expansion
=> add JSONnet containers

concourse/pipelines/container-build.yaml
some containers we build are partial derivatives of other containers we build. reflect these dependencies in build ordering to ensure changes are correctly propagated.
=> add container build deps

concourse/pipelines/linux-image-build.jsonnet, concourse/tasks/certbot-rhui.yaml, concourse/templates/gcp-secret-manager.libsonnet
Add image builds for RHUA and CDS nodes
Introduce a daisy task template for gcloud-get-secret, as we sometimes want to layer in additional inputs to produce a cumulative output, and this isn't possible with external task files
=> Add RHUI builds

concourse/pipelines/artifact-releaser-autopush.yaml
This job is only to test what identity is apparent to the workers. It can be removed later.
=> add curl identity validation job

concourse/pipelines/container-build.yaml
This is to resolve a bootstrapping problem. The c-i-t repo is public and permits unauthenticated pulls.
=> publish forked registry resource to c-i-t repo

concourse/pipelines/linux-image-build.jsonnet
use the new forked registry-image resource to pull a private image for use in the pipeline. if this works, we will move all our internal-use tooling images to this resource type.
=> use new forked image resource

concourse/pipelines/linux-image-build.jsonnet
The auto-determined bucket name for daisy is invalid due to the legacy project identifier.
=> use specified GCS bucket for rhui build

concourse/pipelines/linux-image-build.jsonnet
Migrating Enterprise Linux builds to use secret manager
/hold
=> Migrating Enterprise Linux builds to use secret manager

concourse/pipelines/linux-image-build.jsonnet
remove trailing slash, this produces a matching regex with double slashes, which seems to prevent version generation
change to hyphen instead of underscore in secret
=> prune trailing slash

concourse/pipelines/container-build.jsonnet
This fixes the `upload-daisy-binaries` step which is currently failing with `sh: illegal option -`.
=> Daisy bin publish: Fix 'sh: illegal option -'

concourse/pipelines/container-build.jsonnet
This adds a container build for daisy test runner. Daisy test runner is mainly used for e2e testing of Daisy itself, although there are some historical import/export tests that use it.
Current usages:
1. Legacy import/export tests: [link](https://github.com/GoogleCloudPlatform/compute-image-tools/tree/1ebac650d703c1fc651f7b31ca05de1f73c8d670/daisy_integration_tests)
2. New daisy e2e tests: [link](https://github.com/GoogleCloudPlatform/oss-test-infra/blob/master/prow/prowjobs/GoogleCloudPlatform/gcp-guest/compute-daisy.yaml)
1. Checked out compute-daisy.
2. Executed `docker build -f daisy_test_runner.Dockerfile .`
5. Invoked the container as Prow would.
=> Container build for "daisy test runner"

concourse/pipelines/container-build.jsonnet
Currently this is invoked for every change in `compute-daisy`, so the correct location is `latest` rather than `release`. In a following PR I'll add the `release` target -- we'll probably want to talk offline whether `release` should use the same tagging mechanism that we used in `compute-image-tools`.
Also, this ensures that the release artifacts are public.
This was reported in https://github.com/GoogleCloudPlatform/compute-image-tools/issues/1868
=> daisy binaries: use latest, ensure public

concourse/pipelines/linux-image-build.jsonnet
append rather than overwriting; the workflow itself is in compute-image-tools
=> cds image build: correct input

concourse/pipelines/bare-metal-image-build.yaml, concourse/pipelines/debian-worker-image-build.yaml
We are not reading credentials in a hard-coded way, so these args are not useful anymore.
=> remove unused arg 'gcs-key.credential'

container_images/cleanerupper/Dockerfile, container_images/concourse-metrics/Dockerfile, container_images/gobuild/Dockerfile, container_images/gointegtest/Dockerfile, container_images/gotest/Dockerfile, container_images/jsonnet-go/Dockerfile, container_images/validate-integtest/Dockerfile, imagetest/Dockerfile
The `gointegtest` build is failing with the following message; this occurred since it doesn't pin the golang layer, and Go 1.18 deprecated `go get`
```
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```
`go get no longer builds or installs packages in module-aware mode. `: https://tip.golang.org/doc/go1.18
=> use golang:1.13 everywhere

concourse/pipelines/debian-worker-image-build.yaml, packagebuild/workflows/build_deb11_arm64.wf.json
For a new workflow, this arg is removed on daisy workflows of compute-image-tools. Don't pass it in.
=> remove unused arg 'google_cloud_repo' for debian-11-worker-arm64

concourse/pipelines/debian-worker-image-build.yaml, concourse/tasks/daisy-build-images-debian.yaml, packagebuild/workflows/build_deb11_arm64.wf.json, packagebuild/workflows/build_package.wf.json
Only us-central1-a supports arm64 VM now. Specify it.
Also deprecate google_cloud_repo for debian-worker completely.
=> specify zone=us-central1-a for debian-11-worker-arm64

concourse/tasks/daisy-build-images-debian.yaml
Modify zone of 'daisy-build-images-debian' to us-central1-a for arm compatibility.
There are many "zone" settings in the whole chain of ARM build process. This one is missed in the previous PR.
=> Modify zone of 'daisy-build-images-debian' to us-central1-a for arm compatibility

concourse/pipelines/debian-worker-image-build.yaml
For some reason, the arg for debian worker image publish was wrong for debian-10-worker. I copied it for debian-11-worker-arm64 so it was also wrong. Fix it for debian-10-worker, and also fix for debian-11-worker-arm64.
=> fix prod publish arg name: source_gcs_path -> gcs_image_path

concourse/pipelines/guest-package-build.yaml
- Renamed inject-guest-agent-staging --> inject-guest-agent-linux-staging
- Renamed promote-guest-agent-stable --> promote-guest-agent-linux-stable
- Added:
- inject-guest-agent-windows-staging
- inject-metadata-scripts-windows-staging
- promote-guest-agent-windows-stable
- promote-metadata-scripts-windows-stable
=> Separating windows package promotion steps

concourse/pipelines/linux-image-build.jsonnet, concourse/templates/arle.libsonnet, concourse/templates/common.libsonnet, concourse/templates/daisy.libsonnet, concourse/templates/gcp-secret-manager.libsonnet
* add RHUI image publish jobs (prod-only for now)
* remove jsonnet functions for various Concourse objects in favor of templates
* use registry-image consistently
output after this minor refactor was confirmed to match the output from before the refactor except for ordering and the changes listed here.
=> add rhui publish tasks

concourse/pipelines/guest-package-build.yaml
Will bring it back when we resolved the build issue on debian 11 arm64.
=> comment out guest-agent-publish-coverage since it is broken 

concourse/pipelines/pipeline-set-pipeline.yaml, concourse/pipelines/rhui-release.yaml
This adds a new pipeline for deploying updated CDS and RHUA images to the RHUIv4 infra. It uses Concourse's [gated pipeline pattern](https://concourse-ci.org/gated-pipeline-patterns.html) to support the following features:
1. The pipeline requires a manual invocation (we can remove this later to implement continuous delivery)
2. Jobs are combined into waves. All of the regions in a wave deploy in parallel, and a wave doesn't start until the previous wave finishes.
For testing, I ran this on the dev cluster using my test project. (I didn't run it against `google.com:rhel-infra`.)
=> Add pipeline for RHUIv4 release

imagetest/test_suites/image_validation/image_validation_test.go, imagetest/test_suites/image_validation/license_test.go, imagetest/test_suites/image_validation/package_test.go, imagetest/test_suites/security/image_security_test.go
* skip custom hostname tests
* add 2 missing licenses
* add logic to use correct package manager
the shutdown script time test is still failing - this is more or less a genuine failure and i want to try to resolve it rather than adding a skip, at least right now
output:
```xml
<testsuites name="" errors="0" failures="1" disabled="0" skipped="2" tests="40" time="0">
<testsuite name="security-ubuntu-2204-lts" tests="4" failures="0" errors="0" disabled="0" skipped="0" time="0">
<testcase classname="security-ubuntu-2204-lts" name="TestKernelSecuritySettings" time="0"></testcase>
<testcase classname="security-ubuntu-2204-lts" name="TestAutomaticUpdates" time="0.01"></testcase>
<testcase classname="security-ubuntu-2204-lts" name="TestPasswordSecurity" time="0"></testcase>
<testcase …
```
=> changes to CIT for ubuntu images

concourse/pipelines/container-build.jsonnet, container_images/concourse-metrics/Dockerfile, container_images/jsonnet-go/Dockerfile, container_images/validate-integtest/Dockerfile
#424 was a bit overly broad, and should only have targeted package-building containers.
* restore golang version for other containers
* temporarily disable gce_image_publish until ready to migrate with other similar tools
=> Fix containers

concourse/pipelines/rhui-release.yaml
Updates the RHUI deployment pipeline to ensure that staging (and the rest of the deployment) doesn't start _unless_ the manual trigger button was clicked.
=> rhui-release: wire manual-trigger

concourse/pipelines/pipeline-set-pipeline.yaml, concourse/pipelines/rhui-release.jsonnet
This migrates the `rhui-release` pipeline from raw yaml to jsonnet, including the wait-for-stable feature from https://github.com/GoogleCloudPlatform/guest-test-infra/pull/451 .
=> Use jsonnet for RHUI pipeline

imagetest/README.md
The container build configurations were changed in https://github.com/GoogleCloudPlatform/guest-test-infra/pull/442. These instructions need to be updated to handle this.
=> Update container build instructions 

concourse/tasks/gcloud-promote-package.yaml, concourse/templates/arle.libsonnet
Changing the message type to reflect the transition to inserting images and packages to the Spanner DB when they are ready to be released.
- Previously for packages the promote message type indicated that the message should wait in the pub/sub queue to be read for release, switching to insertPackage to write package data to DB.
- For images the ImagePublish type also indicated the message should wait in the pub/sub queue. Now insertImage writes image data to DB.
=> Transition ARLE publish tasks to spanner

concourse/pipelines/artifact-releaser-autopush.yaml, concourse/pipelines/artifact-releaser-test.yaml
Previously there were no tasks in the ARLE testing pipeline to test an image publish without publishing to a public cloud project.
Now referencing a static debian-11 build we can use this entry to test in production.
=> Release testing image to arle prod

concourse/pipelines/artifact-releaser-test.yaml, concourse/pipelines/pipeline-set-pipeline.yaml
Added missing steps for getting necessary repositories, generating credentials, and loading a version.
=> Missing steps in release-testing-image

concourse/pipelines/rhui-release.yaml
Within each region, we start a rolling update, then wait for the version target to be reached. The MIG exposes a "stable" state, which means that all of the nodes are passing their health check.
This PR adds an additional step to wait for this stable signal.
More info on the status fields: https://cloud.google.com/compute/docs/instance-groups/rolling-out-updates-to-managed-instance-groups#group_status
=> RHUI roll-out: Wait for MIGs to be stable

concourse/pipelines/guest-package-build.yaml, concourse/tasks/daisy-build-package-image.yaml, concourse/tasks/image-test-args.yaml
Build the test image by installing the guest-agent arm64 lib, and run it.
To support that, we added machine-type and worker-image as the task args.
=> run ARM tests for guest agent based on test image

concourse/pipelines/guest-package-build.yaml
Machine type became mandatory for not only arm64 test but also amd64 test. We need to specify it to avoid missing args..
=> specify machine type for guest-agent amd64 test

concourse/tasks/get-last-stable-tag.yaml
The tag names are of the form 20220110 or stable-20220110. This change makes it so the `stable-` string is stripped before writing to the file.
=> Strip the word stable from date

imagetest/test_suites/metadata/shutdown_script_test.go
The actual allowed running time period is 90s, not 120s. So let's set the threshold to 80s other than 110s.
=> [guest-agent image test] fix: verify that shut down script executed no less than 80s

concourse/pipelines/guest-package-build.jsonnet, concourse/pipelines/pipeline-set-pipeline.yaml
Unlike previous adoption of templates, I wasn't able to guarantee that the output was unchanged. So this PR moves to templates but also fixes some inconsistencies, and establishes a normal process for all builds. The build step also uploads packages, either to unstable or to staging. Then promote steps follow naturally from there. The windows package builds in guest-agent and compute-image-windows repos are separated out by package.
Tested on devcluster to ensure it applies and dependencies are correct, but there is a risk of breakage due to unavoidable size of the change, so I'll test all jobs except for stable promotions after merging.
=> Use templates for guest package build pipeline

concourse/pipelines/guest-package-build.jsonnet
the derivative image build steps require the compute-image-tools repo for access to the workflows
=> add missing input

packagebuild/workflows/build_el9_arm64.wf.json
The image doesn't exist yet, but this is a part of the bootstrapping process which enables package builds.
=> add el9_arm64 packagebuild workflow

concourse/pipelines/guest-package-build.jsonnet
* move prep steps for stable tag into the optional block
* disable the last-stable-date stuff which is proving too fragile and needs redesign
* only let one of the resulting promotions tag stable since it's repo-specific not package-specific
=> Fix last stable

concourse/pipelines/guest-package-build.jsonnet
The paths for the windows packages in compute-image-windows are incorrect. Added arch and option `.0` suffix. Real files in bucket right now for comparison:
```
compute-image-windows/certgen.x86_64.20220603.00.0@1.goo
compute-image-windows/google-compute-engine-auto-updater.noarch.20220603.00@1.goo
compute-image-windows/google-compute-engine-powershell.noarch.20220603.00@1.goo
compute-image-windows/google-compute-engine-ssh.x86_64.20220603.00.0@1.goo
compute-image-windows/google-compute-engine-sysprep.noarch.20220603.00@1.goo
```
=> correct windows package paths

imagetest/test_suites/image_boot/setup.go
Skip secure boot tests on ARM64
Test passes with change:
```xml
2022/06/06 21:44:49 Running in project gce-image-builder zone us-central1-a. Tests will run in projects: [gce-image-builder]
2022/06/06 21:44:49 using -filter image_boot
2022/06/06 21:44:49 Add test workflow for test image_boot on image projects/bct-prod-images/global/images/debian-11-bullseye-arm64-v20220606
2022/06/06 21:44:49 Done with setup
2022/06/06 21:44:50 Storing artifacts and logs in gs://gce-image-builder-cloud-test-outputs/2022-06-06T21:44:50Z
2022/06/06 21:44:50 running test image_boot/debian-11-bullseye-arm64-v20220606 (ID vz0qw) in project gce-image-builder
2022/06/06 21:48:22 finished test image_boot/debian-11-bullseye-arm64-v20220606 (ID vz0qw) in project gce-image-builder
<testsuites name="" errors="0" …
```
=> skip secure boot test on arm

imagetest/OWNERS
no longer have a need for this split
=> remove imagetest-specific OWNERS file

imagetest/go.mod, imagetest/go.sum, imagetest/test_suites/network/multinic_minimal_network_test.go
The 'ping' binary is not available on ubuntu minimal images. Replace execution of ping binary with a go native ping implementation.
Tested on ubuntu minimal image:
```xml
<testsuites name="" errors="0" failures="0" disabled="0" skipped="0" tests="6" time="0">
<testsuite name="network-daily-ubuntu-minimal-2204-jammy-v20220603" tests="6" failures="0" errors="0" disabled="0" skipped="0" time="0">
<testcase classname="network-daily-ubuntu-minimal-2204-jammy-v20220603" name="TestDHCP" time="0.01"></testcase>
<testcase classname="network-daily-ubuntu-minimal-2204-jammy-v20220603" name="TestDefaultMTU" time="0"></testcase>
<testcase classname="network-daily-ubuntu-minimal-2204-jammy-v20220603" name="TestPingVMToVM" time="8.11"></testcase>
<testcase …
```
=> use direct ping library in multinic test

imagetest/Dockerfile, imagetest/testworkflow.go
Follow 8.3 file naming for windows executables and also support x86 windows images.
Follow up to comments in previous PR https://github.com/GoogleCloudPlatform/guest-test-infra/pull/478#discussion_r892711947
```
2022/06/09 19:02:01 finished test image_boot/debian-10 (ID yplvh) in project pneil-sandbox
2022/06/09 19:04:50 finished test image_boot/windows-w-new-metadata-scripts (ID 4z26w) in project pneil-sandbox
<testsuites name="" errors="0" failures="0" disabled="0" skipped="0" tests="10" time="0">
<testsuite name="image_boot-debian-10" tests="5" failures="0" errors="0" disabled="0" skipped="0" time="0">
<testcase classname="image_boot-debian-10" name="TestGuestBoot" time="0"></testcase>
<testcase classname="image_boot-debian-10" name="TestGuestReboot" time="0"></testcase>
<testcase …
```
=> Follow 8.3 windows file naming and support x86 images

container_images/gobuild/Dockerfile, packagebuild/common.sh
It's a part of the new packages policy. Upgrading the presubmit gobuild version to 1.16 to ensure the compatibility to 1.16 for partners.
Also upgrade version of built-by-google packages to 1.18.3 to ensure google use the latest compiler.
=> [new golang build policy] upgrade presubmit golang version to 1.16

concourse/pipelines/rhui-release.jsonnet
The TCP proxy is currently randomizing traffic to backends when traffic uses a specific route. While we're working on that issue, we've reduced prod to a single region to avoid clients from seeing inconsistent regional backends.
Here's the pipeline's view in the dev cluster:
=> RHUI: Prod currently uses us-east1 only

container_images/daisy-builder/main.sh
the files are named with underscores, but daisy step names must use hyphens. 
Generated workflow:
```json
{
"Name": "build-packages",
"DefaultTimeout": "30m",
"Vars": {
"gcs_path": {
"Value": "${SCRATCHPATH}/packages",
"Description": "GCS path for built packages e.g. gs://my-bucket/packages"
},
"repo_owner": {
"Value": "GoogleCloudPlatform",
"Description": "GitHub repo owner or organization"
},
"repo_name": {
"Description": "Github repo name",
"Required": true
},
"git_ref": {
"Value": "master",
"Description": "Git ref to check out and build"
},
"version": {
"Description": "Version to build"
},
"build_dir": {
"Description": "Directory to build from"
}
},
"Steps": {
"deb9": {
"IncludeWorkflow": {
"Path": "./workflows/build_deb9.wf.json",
"Vars": {
"gcs_path": "${gcs_path}",
"repo_owner": …
```
=> support underscores in packagebuild container

imagetest/test_suites/image_validation/license_test.go
There's a package `libcanberra0` installed on ubuntu images by default that appears to fail the license test because it is spelled 'licence'. Amend the regex to support this spelling.
```xml
<testsuites name="" errors="0" failures="0" disabled="0" skipped="2" tests="9" time="0">
<testsuite name="image_validation-daily-ubuntu-pro-2004-focal-v20220615" tests="9" failures="0" errors="0" disabled="0" skipped="2" time="0">
<testcase classname="image_validation-daily-ubuntu-pro-2004-focal-v20220615" name="TestNTPService" time="0.01"></testcase>
<testcase classname="image_validation-daily-ubuntu-pro-2004-focal-v20220615" name="TestHostname" time="0"></testcase>
<testcase classname="image_validation-daily-ubuntu-pro-2004-focal-v20220615" name="TestFQDN" time="0.01"></testcase>
<testcase …
```
=> support aussie licenses

concourse/pipelines/windows-image-build.jsonnet
This adds Windows 8.1 and 10 21h2 to Concourse. Multiple changes required to facilitate:
- Move prerequisite passed/trigger logic to allow for easier override in ImgPublishJob
- Add/rename relevant variables to accommodate client envs
- Additional build/publish jobs for client builds
=> Add windows client 8.1 and 10 to Windows pipeline

concourse/pipelines/windows-image-build.jsonnet
This will enable Concourse to build and publish Windows 11 (21h2) Enterprise for internal environments.
=> Add Windows11 to Concourse Windows pipeline

concourse/pipelines/guest-package-build.jsonnet, packagebuild/daisy_startupscript_rpm.sh, packagebuild/workflows/build_deb11_arm64.wf.json, packagebuild/workflows/build_el8_arm64.wf.json, packagebuild/workflows/build_el9_arm64.wf.json
- Remove Debian 9 builds (EOL) and move base Debian builds to Debian 10.
- Add test runs for EL8/EL9 x86_64 and aarch64.
=> EL8/EL9 package builds for arm64.

concourse/pipelines/guest-package-build.jsonnet
currently the diagnostics build is triggered by any new commits to compute-image-tools. this is a shared repo, resulting in many unnecessary builds. change the resource to only trigger to changes in the diagnostics dir.
=> only build diagnostics when changed

concourse/pipelines/windows-image-build.jsonnet
With SQL Server 2012 being EOL, we will no longer be building images at this version.
=> Remove SQL Server 2012 from Concourse Windows Builds

concourse/pipelines/windows-image-build.jsonnet
Adds derivative build for SQL 2022 running on Windows Server 2022. Also had to add support for passing in SSMS version, as Microsoft moved away from a universal installer. We may need to pass different versions going forward.
=> Add SQL Server 2022 Preview to Windows pipeline

concourse/pipelines/windows-image-build.jsonnet
Removes EOL SAC Server version from build pipeline as it will no longer be used.
=> Remove Windows Server SAC 20h2 from Concourse

concourse/pipelines/partner-image-validations.jsonnet
Currently 22.10 images aren't being tested.
```
$ gcloud compute images list --no-standard-images --project ubuntu-os-cloud-devel --filter 'family~2210-amd64'
NAME                                               PROJECT                FAMILY                     DEPRECATED  STATUS
daily-ubuntu-2210-kinetic-amd64-v20220828          ubuntu-os-cloud-devel  ubuntu-2210-amd64                      READY
daily-ubuntu-minimal-2210-kinetic-amd64-v20220909  ubuntu-os-cloud-devel  ubuntu-minimal-2210-amd64              READY
```
=> Enable testing of Ubuntu 22.10 (Kinetic Kudu) images

concourse/pipelines/linux-image-build.jsonnet
during development, we called the target project 'testing' to not require MPA. now that the service is launched, we should require MPA for image publishing
=> publish RHUI images to prod

concourse/pipelines/partner-image-validations.jsonnet
Added a list of Ubuntu ARM64 images and `imagevalidationjob` invocation with `-machine_type=t2a-standard-2`.
```
$ gcloud compute images list --no-standard-images --project ubuntu-os-cloud-devel --filter='family~arm64' | awk '{print $3}' | sort | uniq
FAMILY
ubuntu-1804-lts-arm64
ubuntu-2004-lts-arm64
ubuntu-2204-lts-arm64
ubuntu-2210-arm64
ubuntu-minimal-1804-lts-arm64
ubuntu-minimal-2004-lts-arm64
ubuntu-minimal-2204-lts-arm64
ubuntu-minimal-2210-arm64
```
=> Enable testing of Ubuntu ARM64 images

imagetest/test_suites/image_boot/image_boot_test.go, imagetest/test_suites/image_boot/setup.go
Added support for Alma Linux boot test and removed rocky-linux-8 secure boot test skip condition as it is supported.
=> Added support for Alma Linux boot test

concourse/pipelines/windows-image-build.jsonnet
Add official job definitions to build and publish SQL Server 2022 Web, Standard, and Enterprise on Windows Server 2022 and 2019. Needs [PR#2045](https://github.com/GoogleCloudPlatform/compute-image-tools/pull/2045) to go first.
=> Add SQL Server 2022 release versions to Concourse

concourse/pipelines/windows-image-build.jsonnet
Allows us to track success/fail metrics for image publish jobs in Windows builds
=> Add success/failure metrics to imgpublishjob

concourse/pipelines/windows-image-build.jsonnet
This is a follow-up to pull #573
=> Generate timestamp and load into var for image publish.

concourse/tasks/daisy-build-package-image.yaml
Originally 10m, some builds are starting to time out before finishing cleanup. Setting to 20m to allow more time for completion of tasks.
=> Increase timeout for daisy package build pipeline default

packagebuild/workflows/build_deb10.wf.json, packagebuild/workflows/build_deb11.wf.json, packagebuild/workflows/build_deb11_arm64.wf.json, packagebuild/workflows/build_deb9.wf.json, packagebuild/workflows/build_el6.wf.json, packagebuild/workflows/build_el7.wf.json, packagebuild/workflows/build_el8.wf.json, packagebuild/workflows/build_el8_arm64.wf.json, packagebuild/workflows/build_el9.wf.json, packagebuild/workflows/build_el9_arm64.wf.json
Default timeout of 10m has recently become too short for some builds of EL; increasing to 20m to allow proper cleanup.
=> Update timeout thresholds for package builds

packagebuild/workflows/build_package.wf.json
Because 20m isn't enough for EL9. Setting to 30 to allow cleanup; plan to investigate why this is needed so suddenly later on, but this will hopefully unblock a release that needs to happen this week.
=> Update timeout for wait-for-build

packagebuild/workflows/build_el9.wf.json
20m is still not enough; this needs deeper investigation but also need to unblock a different release in the short term.
=> Update EL9 timeout

concourse/pipelines/linux-image-build.jsonnet
After testing that retrieval of the syft source was working on almalinux image builds, add this to all linux image builds.
=> el syft job for all linux images

concourse/pipelines/linux-image-build.jsonnet, concourse/templates/daisy.libsonnet
Add support for the final sbom export destination, by replacing the "tar.gz" suffix with ".sbom.json"
=> Add sbom-destination input variable with .sbom.json file extension

packagebuild/daisy_startupscript_rpm.sh
Without the python3-devel we'll not have the python3 rpm macros available breaking packages requiring them.
=> rpm build: make sure we have python3-devel available

concourse/pipelines/bare-metal-image-build.yaml, concourse/pipelines/debian-worker-image-build.yaml, concourse/pipelines/linux-image-build.jsonnet, concourse/pipelines/windows-image-build.jsonnet, concourse/tasks/generate-build-id-sbom.yaml, concourse/tasks/generate-build-id.yaml, concourse/tasks/generate-id.yaml, concourse/tasks/generate-linux-date.yaml, concourse/templates/common.libsonnet, concourse/templates/daisy.libsonnet
With the current setup, concourse tasks can only create one file. However, we need a tar.gz and sbom.json file, and both need to have the same name so we can associate them.
To ensure they can have the same name, the linux date will be loaded into a local concourse variable. This can be reused in both generate-build-id and generate-build-id-sbom.
=> Load linux date into var, use for tar gz and sbom json naming

concourse/tasks/generate-id.yaml
Forgot to include a quotation in one of the generate-id tasks.
=> quotation mistake

concourse/tasks/generate-id.yaml
Looking at the format of the yaml tasks, the value of "outputs" in the task must be the name of the directory, not the name of the final variable.
If the output file is generate-id/id, "outputs" must equal generate-id, not id.
=> Change name of outputs directory to conform with tee command

concourse/tasks/generate-id.yaml
Echo statement with extra parenthesis caused syntax error.
=> Remove extra parenthesis in the echo statement

concourse/pipelines/pipeline-set-pipeline.yaml, concourse/pipelines/windows-image-build-staging.jsonnet
Enables build and publish to testing for images using the staging Rapture repo. Stripped all publishing tasks to prod and internal for safety.
=> Fork windows image build for staging builds

concourse/pipelines/pipeline-set-pipeline.yaml
Removing env was not as easy as I thought it would be; removing it from pipeline definition to unblock other updates
=> Remove staging windows build from pipeline

concourse/templates/common.libsonnet
The resource type for gcssbomresource needs to equal 'gcs' so that a worker can be found.
=> Change resource type for worker

concourse/pipelines/windows-image-build-staging.jsonnet, concourse/pipelines/windows-image-build.jsonnet
Win 8.1 went EOL in January. We stopped building it, but still needed to clean up references to it.
=> Removing Windows 8.1 from build pipelines

concourse/pipelines/linux-image-build.jsonnet
Right now, the sbom file pattern is the same as tarballs. For example:
```
{
"name": "debian-11-sbom",
"source": {
"bucket": "artifact-releaser-prod-rtp",
"regexp": "debian/debian-11-bullseye-v([0-9]+).tar.gz"
},
"type": "gcs"
},
```
=> Fix sbom file pattern for all Debian images

container_images/gocheck/Dockerfile, container_images/gointegtest/Dockerfile, container_images/gotest/Dockerfile
From the build error:
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
=> Replace go get calls with go install

container_images/registry-image-forked/dockerfiles/alpine/Dockerfile, container_images/registry-image-forked/dockerfiles/ubuntu/Dockerfile
With all the container inception go downloading is causing a pthread issue due security constraints imposed by the container environment - it's not a required operation so lets get rid of it.
=> registry-image-forked: remove go download

concourse/pipelines/container-build.jsonnet, container_images/registry-image-forked/dockerfiles/alpine/Dockerfile, container_images/registry-image-forked/dockerfiles/ubuntu/Dockerfile
Multiple nested layers of containers (two, to be precise) in Concourse build system causes issues with pthreads in CGO runtime. It turned out to be a general issue and not related to one particular sub-command. This happens during container images builds. 
```
INFO[0030] Args: [-c go build -o /assets/in ./cmd/in]   
INFO[0030] Running: [/bin/sh -c go build -o /assets/in ./cmd/in] 
runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0x7f2dfae01a7c m=0 sigcode=18446744073709551610
goroutine 0 [idle]:
runtime: g 0: unknown pc 0x7f2dfae01a7c
stack: frame={sp:0x7ffdfa9f9e60, fp:0x0} stack=[0x7ffdfa1fb3e0,0x7ffdfa9fa3f0)
0x00007ffdfa9f9d60:  0x0000000000000000  0x0000000000000000 
0x00007ffdfa9f9d70:  0x0000000000000000  0x0000000000000000 
0x00007ffdfa9f9d80: …
```
=> Fix 'registry-image-forked' build

imagetest/test_suites/disk/disk_resize_test.go, imagetest/test_suites/image_boot/image_boot_test.go, imagetest/test_suites/image_validation/clock_test.go, imagetest/test_suites/image_validation/image_validation_test.go, imagetest/test_suites/image_validation/license_test.go, imagetest/test_suites/image_validation/linux_license_test.go, imagetest/test_suites/image_validation/package_test.go, imagetest/test_suites/metadata/metadata_test.go, imagetest/test_suites/metadata/shutdown_script_test.go, imagetest/test_suites/metadata/startup_script_test.go, imagetest/test_suites/network/alias_ip_test.go, imagetest/test_suites/network/dhcp_test.go, imagetest/test_suites/network/gvnic_test.go, imagetest/test_suites/network/mtu_test.go, imagetest/test_suites/network/multinic_minimal_network_test.go, imagetest/test_suites/oslogin/oslogin_test.go, imagetest/test_suites/security/image_security_test.go, imagetest/test_suites/ssh/host_key_test.go, imagetest/test_suites/ssh/image_ssh_test.go, imagetest/test_suites/windows/driver_package_test.go, imagetest/test_suites/windows/googet_test.go, imagetest/test_suites/windows_containers/docker_container_test.go, imagetest/test_suites/windows_image_validation/image_validation_test.go
With commit 89ce9742feda23ba1e12b99e758d6d268d5e7c87 we duplicated some of the directives and got it wrong for some, this patch reviews it fix all the mess.
=> fix go build directives all across the repo.

imagetest/Dockerfile
Let's keep all Golang versions consistent.
=> Update Golang version in `cloud-image-tests` for consistency

imagetest/Dockerfile
In the alpine docker image with `edge` tag is observed an issue with OpenSSL library version. This causes most CIT tests to fail. I nailed down the exact place where it happens in the code
https://github.com/GoogleCloudPlatform/guest-test-infra/blob/master/imagetest/fixtures.go#L415
and reproduced the issue in a separate environment:
```
$ docker run --rm -it alpine:edge sh
Unable to find image 'alpine:edge' locally
edge: Pulling from library/alpine
c0b0d1596f27: Already exists 
Digest: sha256:ff8db144214ae3fe9d1b29d3bc352e0e3d4e1dba36a39f65dce4c8b42c37ea77
Status: Downloaded newer image for alpine:edge
/ # apk add --no-cache openssh-keygen
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX …
```
=> Fix OpenSSL version mismatch

packagebuild/daisy_startupscript_deb.sh, packagebuild/daisy_startupscript_rpm.sh, packagebuild/workflows/build_deb10.wf.json, packagebuild/workflows/build_deb11.wf.json, packagebuild/workflows/build_deb11_arm64.wf.json, packagebuild/workflows/build_deb9.wf.json, packagebuild/workflows/build_el6.wf.json, packagebuild/workflows/build_el7.wf.json, packagebuild/workflows/build_el8.wf.json, packagebuild/workflows/build_el8_arm64.wf.json, packagebuild/workflows/build_el9.wf.json, packagebuild/workflows/build_el9_arm64.wf.json
In preparation for generating SBOMs for guest environment first party packages this patch brings the required changes to fetching sbomutil from gcs for debian builds.
=> debian packages: fetch sbomutil from gcs

packagebuild/daisy_startupscript_goo.sh, packagebuild/workflows/build_goo.wf.json
In preparation for generating SBOMs for guest environment first party packages this patch brings the required changes to fetching sbomutil from gcs for googet builds.
=> googet packages: fetch sbomutil from gcs

concourse/pipelines/guest-package-build.jsonnet, packagebuild/workflows/build_package.wf.json
By passing down sbom_util_gcs_root the package build workflow will start fetching the sbomutil binary.
=> package build: pass down sbom_util_gcs_root

concourse/templates/common.libsonnet
sbom: remove root folder on bucket definition
This will break gcs calls for bucket validation.
=> SBOM bucket

concourse/pipelines/linux-image-build.jsonnet, concourse/templates/common.libsonnet
Avoid having custom regexp spread across but reuse the "constructor" instead.
=> gcssbom resource: use the resource's "constructor"

concourse/pipelines/linux-image-build.jsonnet, concourse/templates/arle.libsonnet
We are not using it yet but making sure the sbom path is getting set to arlepublishtask object.
=> arlepublishtask: make sure to pass the sbom's path

concourse/pipelines/linux-image-build.jsonnet, concourse/templates/arle.libsonnet
Make sure we are passing sbom_gcs_path both to arle and gce publish jobs.
=> arle: pass sbom_gcs_path to all jobs of interest

concourse/pipelines/linux-image-build.jsonnet, concourse/templates/common.libsonnet
Adds debian-12 and debian-12-arm64 image build and test pipeline.
=> Add bookworm to Concourse image build

packagebuild/daisy_startupscript_rpm.sh, packagebuild/test_build.sh
It turned out that Centos7 is the only platform among all we support on GCE at the moment that has a pretty ancient GCC available in the standard repos. It is gcc 4.8.5  when all others have minimum gcc 8 and higher (most of them has at least gcc 10). The problem I faced is that GCC (g++ specifically)  before ver 5 doesn't support one needed and  important feature.  To be certain, it doesn't have a copy constructor for fstream classes.
The official way to bring a newer version of GCC to Centos7 is installing Software Collections and then, Devtoolset with a needed version of GCC. That's what I integrated in the existing building script for RPMs and pinned installation of these extra packages for only EL7.
By the way, it doesn't correlate with the existing Build dependency `gcc-c++` (which …
=> Use GCC 10 for EL7 rpm package builds

packagebuild/daisy_startupscript_rpm.sh
It seems both rpm and source rpm are being create in the RPM directory.
=> sbom: fix rpm file lookup

packagebuild/daisy_startupscript_rpm.sh
The binary packages are being written to /usr/src/redhat/SRPMS/ and /usr/src/redhat/RPMS/ respectively, the command to find it was missing plural suffix in the directory name i.e SRPM instead of SRPMS and RPM instead of RPMS.
This change also make sure to lookup only within SRPMS directory since we are interested on the source rpm.
=> sbom: fix the path we are looking up source rpms

packagebuild/common.sh
When checking if sbom was already previously generated we inverted the boolean condition check.
=> sbom: fix an inverted boolean check

concourse/pipelines/guest-package-build.jsonnet, packagebuild/common.sh
Make sure to properly deploy sbomutil for the right architecture.
=> sbom: add support to arm64

packagebuild/daisy_startupscript_rpm.sh
In the rpm builds we don't have BUILD_DIR variable defined, this change assumes (as all the remaining of the build script does) that PWD is the build dir.
=> sbom: fix the call to generate_and_push_sbom for rpm build

concourse/pipelines/guest-package-build.jsonnet
This patch addes the sbomfile field to all package publishing pubsub calls, the googet ones are intentionally left as no-op(leaving the object field empty will cause ARLE to ignore the field).
=> sbom: add sbomfile to ARLE's pubsub call

packagebuild/daisy_startupscript_deb.sh
Use the MDS IP for our package build until we resolve this.
=> On Debian 12 the guest is not getting the right search domains

concourse/pipelines/guest-package-build.jsonnet
Based on the documented behavior this resource will only yield new versions when cli_tools/diagnostics/** gets changed by a commit. This patch makes sure to remove it and allow us to get new versions for any new changes commited.
=> packages: fix compute-image-tools git-resource definition

concourse/pipelines/linux-image-build.jsonnet
Instead of using the syft tar file to generate the SBOM for linux images, use sbomutil.
=> Migrate from syft source to sbom util source

concourse/pipelines/linux-image-build.jsonnet
The variable sbom_util_gcs_path should be renamed sbom_util_gcs_root
=> Fix sbom util path name error

imagetest/test_suites/image_validation/image_validation_test.go, imagetest/test_suites/network/setup.go, imagetest/test_suites/security/image_security_test.go
Most all modern distros now are going to have systemd-resovle and therefore that port is fairly normal.
There are still many failing test cases we're looking into.
=> Fix a couple test cases for Debian 12.

concourse/pipelines/windows-image-build.jsonnet
Pass in sbom destination to daisy workflows, so the default value of "." is not used
=> Pass in sbom_destination

concourse/pipelines/windows-image-build.jsonnet
SBOM destination was not properly being passed in before.
After rendering with the jsonnet command, this likely passes it in correctly.
=> Pass sbom destination on the correct line

concourse/pipelines/artifact-releaser-test.jsonnet
Concourse is erroring across all groups, stating that it cannot find the appropriate resource type `registry-image-forked` for platform `linux`. This should fix that issue.
=> Add registry-image-forked resource type to artifact-releaser-test.

concourse/pipelines/artifact-releaser-test.jsonnet
Delete the 'autopush' environment because it is not used in the new task.
=> Switch image publishing method from gcepublishtask to arlepublishtask

concourse/pipelines/artifact-releaser-test.jsonnet
The reason for this is because we keep getting an error in concourse saying that the `tag` field is an unknown field. Along with this change is cleaning up `resource_types` and removing the `registry-image-forked` resource type. 
One consideration was removing the `tag` from the `publishresulttask` implementation in `templates/common.libsonnet`. However, from looking through the documentation specific to `registry-image-forked`, it causes slightly different behavior (instead of focusing on the `latest` tag, it looks at semvers instead) which may not be desired, and thus we leave that task alone and create our own working implementation of it.
=> Create separate publish task for artifact-releaser-test.

concourse/pipelines/guest-package-build.jsonnet
The resource being generated is not consistent with name passed in to arle, the signing job will try to sign the wrong file (or a non existing package file).
=> windows: fix certgen upload resource name

concourse/pipelines/container-build.jsonnet
Make sure we are building daisy statically; additionally we are
updating the container image to be consistent across the other
build environments.
=> daisy: build daisy statically & update container image

concourse/pipelines/container-build.jsonnet
We assumed that the format <repository>:<tag> was valid for concourses registry-image-resource, however tag needs to be specified with the tag field in the resources configuration.
=> daisy: properly set the container tag

concourse/pipelines/artifact-releaser-test.jsonnet, concourse/templates/common.libsonnet
This should completely isolate the two environments.
=> Copy packages from prod to autopush for ARLE testing pipeline

imagetest/fixtures.go, imagetest/test_suites/image_validation/clock_test.go
Change the way the ntp test is run to use commands, functionality should remain the same
=> Use ntp commands instead of reading files for test

concourse/pipelines/artifact-releaser-test.jsonnet
Skip upload if an object already exists and we don't need to grant delete permission.
=> Skip upload if already exists

concourse/pipelines/artifact-releaser-test.jsonnet
Fix certgen file name, and make the tag filter even more stringent to avoid cases where the tag is, for example, 20180708a, which would make the pipeline fail.
=> Fix more minor issues with artifact releaser testing pipeline

concourse/pipelines/artifact-releaser-test.jsonnet
At some point, it seems like the directory was changed from `artifact-registry-apt-transport` to `apt-transport-artifact-registry`.
=> Fix directory for apt transport artifact registry package

imagetest/fixtures.go, imagetest/testworkflow.go, imagetest/testworkflow_test.go
Reverts GoogleCloudPlatform/guest-test-infra#738
It appears that there are two potential issues which need to be resolved, and currently the image releases are blocked by failing tests. It is probably a good idea to revert this change until this is fixed.
1. there is likely a disk name conflict due to global unique disk names
2. The source image field of initparams likely needs to be set
=> Revert "Support multiple disks in a VM"

imagetest/test_suites/disk/disk_resize_test.go, imagetest/test_suites/image_boot/image_boot_test.go, imagetest/test_suites/network/alias_ip_test.go
In the network/disk/boot tests we try to assess if the boot marker
file exists and if it doesn't exist we try to create it, but always
run into t.Fatal() even if we succeeded.
=> test: don't fail if we succeed to create marker file

imagetest/fixtures.go, imagetest/testworkflow.go, imagetest/testworkflow_test.go
Functionality of the current tests should not change. This should allow a future change to create a test vm with 2 or more disks.
=> Allow test vm to have multiple disks

imagetest/test_suites/storage_perf/setup.go, imagetest/testworkflow.go
c3 boot disk must be pd balanced, not pd standard.
=> Allow hyperdisk testing by changing boot disk

imagetest/fixtures.go, imagetest/fixtures_test.go, imagetest/test_suites/storage_perf/setup.go, imagetest/testworkflow.go, imagetest/testworkflow_test.go
Instead of passing the c3 machine type in the command line, make the tests able to pass in the machine type, such as for the hyperdisk test.
=> Pass in machine type to fixtures

imagetest/utils/test_utils.go
Simplifies having to import and run runtime.GOOS in every test suite targeting windows and linux.
=> Add IsWindows to test utils

imagetest/test_suites/image_boot/image_boot_test.go
Previous check only verified that secure boot was enable in the EFI settings, not that the systems was booted with it.
=> Confirm a PK is enrolled when checking secure boot state on linux systems

imagetest/test_suites/imageboot/image_boot_test.go, imagetest/test_suites/imageboot/setup.go
Reasons for exceptions to this test:
Debian 10 & 11 don't support secure boot on ARM.
Debian 12 supports secure boot on ARM and is currently working but it it's not enabled with the FAI build infra we're using for cloud images. Waiting to hear from Debian on whether they'll enable it upstream, otherwise we will do it and remove the exception.
Windows server 2012 core is working but difficult to test because the powershell secureboot cmdlet for checking if secure boot is enabled is not included by design on server core. It's EOL in less than 2 months anyway.
Rocky, RHEL, and SLES don't have signed shims for ARM. I've included a link to a ticket for tracking in the comments.
=> Expand secure boot test to cover supported images on ARM

imagetest/cmd/manager/main.go, imagetest/test_suites/sql/setup.go, imagetest/test_suites/sql/sql_test.go
Initial commit of basic sql version testing.  Verifies 3 test cases:
1. Installed Sql Server edition matches the image (i.e. Web/Standard/Entierprise)
2. Installed Sql Server version matches the image (i.e. Sql Server 2022)
3. Installed Windows Server version matches the image (i.e. Windows Server 2022)
=> Create sql test suite

imagetest/fixtures.go, imagetest/test_suites/networkperf/performance_test.go, imagetest/test_suites/networkperf/setup.go, imagetest/test_suites/networkperf/startupscripts/windows_clientstartup.ps1, imagetest/test_suites/networkperf/startupscripts/windows_serverstartup.ps1
It's weird how the network performance test results don't reach anywhere close to the targets, especially in the non-Tier1 network tests (specifically for Windows)
=> Update networkperf test suite to support windows images

imagetest/test_suites/imagevalidation/image_validation_test.go
It appears that the forced zonal DNS rollout has broken this case.
=> Skip FQDN test on EL9.

concourse/pipelines/linux-image-build.jsonnet, concourse/pipelines/windows-image-build-standard.jsonnet
Tag windows and linux release pipeline test jobs with serial groups to limit how many jobs run at once
=> Enable release testing in windows release pipelines

imagetest/testworkflow.go
It seems like the order of checking the steps can result in a nil pointer in the build, if machineType is not set.
=> Fix nil error in build

imagetest/test_suites/cvm/setup.go
=> Skip arm images in CVM testing

imagetest/test_suites/cvm/setup.go
Tthey aren't tagged for it and it doesn't work on a manually tagged image.
=> Add rhel sap 8.1 and 8.2 cvm exclusions

imagetest/test_suites/oslogin/oslogin_test.go
The new implementation removes the use of one of the PAM modules and introduces AuthorizedPrincipalsCommand.
=> oslogin test: update tests based on new authorization implementation

imagetest/test_suites/storageperf/setup.go
Timing out on testgrid: https://testgrid.k8s.io/googleoss-gcp-guest#cit-periodics-performance
Not 100% sure I skipped this correctly, lmk if this is a problem.
=> Skip the c3d family during storageperf testing on windows 2012 and 2016

concourse/pipelines/container-build.jsonnet, container_images/citpresubmit/Dockerfile, container_images/citpresubmit/main.sh
There are multiple things wrong with the way presubmits are running on CIT:
1) The globbing on the go cli is package globbing not file globbing, so it doesn't pick up the imagetest folder in gobuild because it has it's own go.mod file
2) Even if it did run the logic in those cases it wouldn't make a lot of sense because the "test code" in CIT isn't really test code in the usual sense so running `go test` on it is incorrect, it just needs to build instead of pass
3) The test code that is typical test code (testworkflow_test.go, etc). isn't being run during gotest because of issue 1.
The only thing that does get picked up is gofmt, because that uses `find . -name *.go` to select files instead of the go cli globbing.
=> Add CIT presubmit container

container_images/citpresubmit/Dockerfile
The presubmit currently can't find the go-junit-report command, this should fix that.
=> Install go-junit-report in the cit presubmit container

container_images/citpresubmit/main.sh
Previous container is not executing tests in the right directory without $BUILD_DIR
=> Change to imagetest directory in CIT presubmit even when $BUILD_DIR is unset

container_images/citpresubmit/Dockerfile
Make the citpresubmit Dockerfile match the one for gotest, in case some dependency prevents go-junit-report from being installed
=> Install all dependencies for dockerfile

imagetest/fixtures.go, imagetest/utils/test_utils.go
A format string in test_utils.go was using the wrong formatter for an int64
A check for networking tier in fixtures.go always returns true. I changed it to be in line with what the log message implies.
=> Fix existing presubmit failures that slipped through the presubmit gap.

imagetest/fixtures.go, imagetest/test_suites/storageperf/setup.go, imagetest/utils/test_utils.go
On some operating systems such as centos-stream-8 and rhel-7, the lsblk json size field is enclosed in quotes, making it a string.
On other operating systems, it can be directly parsed as an int64 number.
This change allows both cases to be handled.
=> Fix json unmarshal error

imagetest/utils/test_utils.go
Linux lsblk command has a minor bug, which appears in the EL7 tests
=> Remove dash in linux command

imagetest/utils/test_utils.go
On el7, there was a bug where lsblk parsing would cause an error.
This fix ensures that we only need to find one line with the correct disk partition size. The lsblk output has lines which we know are not the correct partition, such as the title line. For those lines, we want to keep parsing until we find the correct line, instead of returning an error.
=> Fix el7 disk partition condition

imagetest/test_suites/storageperf/iops_read_test.go, imagetest/test_suites/storageperf/iops_write_test.go, imagetest/test_suites/storageperf/setup.go, imagetest/test_suites/storageperf/startupscripts/install_fio.ps1, imagetest/test_suites/storageperf/storage_perf_utils.go
Do not initialize the mount disk on windows. This fixes the fio write permissions issue.
=> Windows write test fix

imagetest/cmd/manager/main.go, imagetest/fixtures.go, imagetest/fixtures_test.go, imagetest/test_suites/networkperf/performance_test.go, imagetest/test_suites/networkperf/setup.go, imagetest/testworkflow.go, imagetest/testworkflow_test.go
This PR also
- Does some minor cleanup in `fixtures.go` regarding `CreateNetwork`, making the MTU setting a separate method instead of a copy-paste of `CreateNetwork` with one extra parameter.
- Refactors `networkperf` test suite to take advantage of the now-available machine type field. We pass the target number directly instead of a large map string.
- Also use the `MachineType` to prevent `Tier_1` tests from running if the machine type is not supported.
=> Pass down machine types through TestWorkflow

imagetest/test_suites/storageperf/iops_read_test.go, imagetest/test_suites/storageperf/iops_write_test.go, imagetest/test_suites/storageperf/setup.go
Ubuntu 16 has an old version of fio, so one of the argument names is different.
Also, for unclear reasons, ubuntu 16 tests on the c3 machine type hang.
=> Ubuntu 16 fix

imagetest/cmd/wrapper/main.go
The metadata test is sometimes failing: investigate whether this is due to putting the guest attributes as the instance signal
=> Rollback guest attribute call until fixed

concourse/pipelines/windows-image-build-mbr.jsonnet
Adds MBR builds as a separate pipeline to be run ad-hoc
=> Fork Concourse windows image build pipeline for MBR

imagetest/cmd/manager/main.go, imagetest/fixtures.go, imagetest/go.mod, imagetest/go.sum, imagetest/test_suites/shapevalidation/setup.go, imagetest/test_suites/storageperf/setup.go, imagetest/testworkflow.go
During testing I ran into a lot of problems with finding free quota that was taken by the time vm creation started. Some of this is unavoidable because daisy takes a second to switch between steps, but I mitigated the problem by staggering parallel workers. Most of this can be avoided by just waiting 60-90 seconds after starting a workflow.
The other thing I did was break this up from one large wait-for-quota step that all creation steps depend on, to quota steps for each create step. But the only create step that actually needs enough quota to worry about right now is the create VMs step, so I just took the others out avoid to avoiding leaving in unused code.
If it's not clear enough that the existing API is only for quota that gates VM creation I can add some comments expanding on this …
=> Add wait for vm quota test workflow step, and functions to append quotas

imagetest/cmd/wrapper/main.go, imagetest/testworkflow.go, imagetest/utils/test_utils.go
Previously, guest attributes were leading to the metadata shutdown script test failing due to reboot behaviors. This should fix the issue.
=> Add back guest attributes with fix for metadata shutdown test

imagetest/fixtures.go, imagetest/fixtures_test.go
Unit test this function
Current build panics when generating workflows that wait for quota: https://oss.gprow.dev/view/gs/oss-prow/logs/cit-periodics-performance/1710038937394745344
=> Fix nil ptr in WaitForVMQuota

concourse/pipelines/pipeline-set-pipeline.yaml
Adds the MBR pipeline to the setting of pipelines. Also removes the Standard edition Windows Server from the active pipelines (but not removing the config in case it is needed later).
=> Enable MBR Windows pipeline, remove standard Windows pipeline

concourse/pipelines/windows-image-build-mbr.jsonnet
Less confusing to read, also matching the naming convention used in the UEFI build pipeline.
=> Update MBR build pipeline image/workflow naming

concourse/pipelines/windows-image-build-mbr.jsonnet
Prevents collision for sboms, and makes job build names easier to distinguish from uefi
=> Update image and sbom naming for MBR pipeline

imagetest/test_suites/shapevalidation/setup.go
=> Wait for CPUS instead of N1 CPUs during N1 shape validation

imagetest/cmd/wrapper/main.go, imagetest/fixtures.go, imagetest/test_suites/metadata/setup.go, imagetest/testworkflow.go
Minor change to the wait step for tests running the shutdown scripts.
This is in preparation for adding guest attributes: after a follow up change, the first boot of the shutdown script will wait for a guest attribute with a special name. This should make the shutdown script test robust even after using guest attributes instead of the serial log.
=> Shutdown Script Minor Change

imagetest/test_suites/imageboot/setup.go
"imageboot-opensuse-leap-arm64: TestGuestSecureBoot" failing repeatedly: https://oss.gprow.dev/view/gs/oss-prow/logs/cit-periodics/1712071098494881792
/cc @zmarano @jjerger @drewhli @koln67
=> Skip broken secureboot test on opensuse-leap arm

concourse/pipelines/windows-image-build-standard.jsonnet
I don't think anything uses this but the linux pipeline but I know the current configuration does not function correctly so might as well fix it.
/cc @jjerger @zmarano
=> Fix windows-image-build-standard publish-to-prod pipelines and align test configuration with linux pipelines

imagetest/test_suites/hotattach/hot_attach_test.go
Use computepb instead of compute for hotattach calls, so that we can wait() until the calls complete.
=> Wait calls for hotattach

imagetest/cmd/wrapper/main.go, imagetest/testworkflow.go, imagetest/utils/test_utils.go
Add support for a 2nd guest attribute, which is used on the first boot of tests which require both a reboot and the second boot's test run to overwrite the first boot's test run.
Currently, this special case only applies to shutdown script tests.
=> Shutdown attribute

concourse/pipelines/windows-image-build-staging.jsonnet
Separating a PR to catch up the staging pipeline to the current state of the release pipeline before testing additional changes.
=> Catch up Windows Staging pipeline to current state

concourse/pipelines/windows-image-build-mbr.jsonnet
Temporary so that we don't flood bct with images during implementation testing
=> Remove publish from mbr build

imagetest/test_suites/networkperf/performance_test.go, imagetest/test_suites/networkperf/setup.go
/cc @zmarano @drewhli 
Debian 12 arm and x86 results:
```
<testsuites name="" errors="0" failures="4" disabled="0" skipped="0" tests="54" time="0">
<testsuite name="networkperf-debian-12-arm64" tests="6" failures="2" errors="0" disabled="0" skipped="0" time="0">
<testcase classname="networkperf-debian-12-arm64" name="TestGVNICExists" time="0"></testcase>
<testcase classname="networkperf-debian-12-arm64" name="TestGVNICExists" time="0"></testcase>
<testcase classname="networkperf-debian-12-arm64" name="TestNetworkPerformance" time="0.01">
<failure type="">    performance_test.go:57: Error: Did not meet performance expectation on machine type t2a-standard-1 with network default-network-t2a-standard-1-networkperf-p26h4. Expected: 8.5 Gbits/s, Actual: 1.78 Gbits/s</failure>
</testcase> …
```
=> Run networkperf on multiple machine types, defined in test setup.

imagetest/test_suites/networkperf/setup.go
Multiply quotas correctly to wait on the appropriate number of CPUs
Wait for even small quotas of CPUs
Fixes for failures in testgrid
/cc @jjerger @koln67 @zmarano @drewhli
=> Create disks for networkperf images based on VM zone

imagetest/testworkflow.go
See comment for justification, and the latest results on the screwed up testgrid for impact.
=> Revert using the compute API for test result names.

imagetest/test_suites/storageperf/setup.go
Debian 10 was somehow not skipped on appropriate machine types from the previous check, this one works
Skip windows images based on family name not image name.
=> Add a required features section to storage perf test config and specify GVNIC for instances that require it.

imagetest/test_suites/networkperf/performance_test.go, imagetest/test_suites/networkperf/setup.go
```
<testsuites name="" errors="0" failures="2" disabled="0" skipped="0" tests="18" time="0">
<testsuite name="networkperf-debian-12" tests="18" failures="2" errors="0" disabled="0" skipped="0" time="0">
<testcase classname="networkperf-debian-12" name="TestGVNICExists" time="0"></testcase>
<testcase classname="networkperf-debian-12" name="TestGVNICExists" time="0"></testcase>
<testcase classname="networkperf-debian-12" name="TestNetworkPerformance" time="0"></testcase>
<testcase classname="networkperf-debian-12" name="TestGVNICExists" time="0"></testcase>
<testcase classname="networkperf-debian-12" name="TestGVNICExists" time="0"></testcase>
<testcase classname="networkperf-debian-12" name="TestNetworkPerformance" time="0.01"></testcase>
<testcase classname="networkperf-debian-12" …
```
=> Report network tier correctly in networkperf

imagetest/test_suites/hostnamevalidation/hostname_validation_test.go, imagetest/test_suites/hostnamevalidation/setup.go, imagetest/test_suites/packagevalidation/clock_test.go, imagetest/test_suites/packagevalidation/package_test.go, imagetest/test_suites/packagevalidation/setup.go, imagetest/test_suites/windowsimagevalidation/image_validation_test.go, imagetest/utils/test_utils.go
Proposed paradigm for windows image migration: until all test behavior is merged, use utils.LinuxOnly() or utils.WindowsOnly()
=> More windows migration

.gitignore, imagetest/build.sh, imagetest/cmd/wrapper/main.go, imagetest/test_suites/disk/disk_resize_test.go, imagetest/test_suites/hostnamevalidation/hostname_validation_test.go, imagetest/test_suites/imageboot/image_boot_test.go, imagetest/test_suites/licensevalidation/license_test.go, imagetest/test_suites/licensevalidation/linux_license_test.go, imagetest/test_suites/metadata/metadata_test.go, imagetest/test_suites/metadata/shutdown_script_test.go, imagetest/test_suites/metadata/startup_script_test.go, imagetest/test_suites/network/alias_ip_test.go, imagetest/test_suites/network/dhcp_test.go, imagetest/test_suites/network/gvnic_test.go, imagetest/test_suites/network/mtu_test.go, imagetest/test_suites/network/multinic_minimal_network_test.go, imagetest/test_suites/networkperf/gvnic_test.go, imagetest/test_suites/networkperf/performance_test.go, imagetest/test_suites/packagevalidation/clock_test.go, imagetest/test_suites/packagevalidation/googet_test.go, imagetest/test_suites/packagevalidation/package_test.go, imagetest/test_suites/packagevalidation/windows_version_test.go, imagetest/test_suites/security/image_security_test.go, imagetest/test_suites/sql/sql_test.go, imagetest/test_suites/ssh/host_key_test.go, imagetest/test_suites/ssh/image_ssh_test.go, imagetest/test_suites/storageperf/iops_read_test.go, imagetest/test_suites/storageperf/iops_write_test.go, imagetest/utils/metadata.go, imagetest/utils/test_utils.go
Remove duplicate methods and stop assuming instance attributes for all calls, let the callers decide the metadata root level.
=> util: unify metadata code

imagetest/test_suites/mdsmtls/mds_mtls_test.go, imagetest/test_suites/mdsmtls/setup.go
Add basic mTLS MDS tests to verify credentials are bootstrapped and exists at expected location
*Note: Tests are not enabled yet on purpose*
=> Add mTLS MDS tests to verify credentials exists

imagetest/test_suites/oslogin/oslogin_test.go
The OS Login stack will only have the sshd's PAM config containing the pam_oslogin_login.so module when two factors authentication is enabled.
=> oslogin: only test sshd's PAM config if 2fa is enabled

imagetest/test_suites/oslogin/oslogin_test.go, imagetest/utils/metadata.go
Considering that non existing 2fa MDS entry is assumed as "non enabled" this patch changes the metadata utils to report a known error for 404 errors, if the entry is not found we assume the flag to be disabled.
=> oslogin: 2fa MDS entry will not always be present

imagetest/Dockerfile, imagetest/cmd/manager/main.go, imagetest/local_build.sh, imagetest/testworkflow.go
Allow local testing for builds so the dev process is faster, though currently only supported for one test suite at a time and AMD 64 linux
Example invocation (assuming zone, project, and images are set, and this is run from the imagetest folder):
outspath=/home/username/out
./local_build.sh -o $outspath -s disk
cd $outspath
./manager -zone $ZONE -project $PROJECT -images $images -filter disk -local_path $outspath
Alternatively, if invoking from another folder, the imagetest root can be passed in.
If invoking from guest-test-infra, 
./imagetest/local_build.sh -o $outspath -s disk -i imagetest
=> Imagetest local build support

imagetest/fixtures.go, imagetest/fixtures_test.go, imagetest/testworkflow.go, imagetest/testworkflow_test.go
The abstraction of setting one of instance or instancebeta is not super elegant but it matches the abstractions present in daisy. There is no unified way to represent a compute instance which is either GA or beta. Generics are not an option because we can't directly reference arbitrary properties on instiated generic types, something we need to do frequently.
Added support for beta instances in existing TestVM methods. Expanded unit tests for TestVM methods to cover instancebeta cases. I modified the behavior in a couple TestVM methods which were clobbering ShieldedInstanceConfig, it's now possible to enable both secure boot and shielded vm in the same instance without them clobbering each other.
Added a function to create a TestVM from a daisy.InstanceBeta and a slice of compute (GA) …
=> Add the ability for TestVM to run on an instance from the beta API.

imagetest/Dockerfile, imagetest/go.mod
It builds and runs:
```
acrate@acrate-p1g4 ~/g/g/imagetest (citimage)> sudo docker run -v ~/.config/gcloud:/creds -e GOOGLE_APPLICATION_CREDENTIALS=/creds/application_default_credentials.json cit -project compute-image-test-pool-001 -zone us-central1-a -images projects/debian-cloud/global/images/family/debian-11-arm64 -filter "imageboot" -timeout 10m
2023/11/02 23:15:26 Running in project compute-image-test-pool-001 zone us-central1-a. Tests will run in projects: [compute-image-test-pool-001]
2023/11/02 23:15:26 using -filter imageboot
2023/11/02 23:15:26 Add test workflow for test imageboot on image projects/debian-cloud/global/images/family/debian-11-arm64
2023/11/02 23:15:27 Done with setup
2023/11/02 23:15:28 Storing artifacts and logs in …
```
=> Update packages in cloud-image-tests container and bump golang version to 1.20

concourse/pipelines/windows-image-build-staging.jsonnet, concourse/pipelines/windows-image-build-standard.jsonnet, concourse/pipelines/windows-image-build.jsonnet
Remove Mirantis builds from concourse pipelines; update all pipelines to only support Docker CE for internal usage
=> Removing Mirantis Docker builds from Concourse

concourse/pipelines/guest-package-build.jsonnet
base_buildpackagejob is missing extended_tasks field declaration.
=> package-build: add missing field

container_images/citpresubmit/main.sh, container_images/gotest/main.sh, container_images/registry-image-forked/in_test.go
We are missing a lot of gobuild/gocheck/gotest coverage because these containers are scoped to only subdirectories which belong to the same module as the main directory. This change will modify the citpresubmit container to either build CIT or test it based on the argument given to the container. This should be accompanied by the change in guest-test-infra presubmit configuration to check/test/build each module in guest-test-infra separately.
This also includes a fix for registry-image-forked's `gocheck` presubmit, which would otherwise fail because it's accessing linux only APIs in a file that's not scoped for linux builds only.
=> Revamp guest-test-infra presubmit checks

concourse/pipelines/guest-package-build.jsonnet
In the guest-agent-dev pipeline we don't want to have tags added to github in a successful build.
=> guest-agent-dev: don't add tags to github

container_images/citpresubmit/main.sh
Seems to be working fine: https://storage.googleapis.com/oss-prow/pr-logs/pull/GoogleCloudPlatform_guest-test-infra/912/infra-presubmit-gobuild-cit/1723067726181699584/build-log.txt
=> Block CIT submission on successful workflow generation

imagetest/test_suites/storageperf/iops_read_test.go, imagetest/test_suites/storageperf/iops_write_test.go, imagetest/test_suites/storageperf/setup.go, imagetest/test_suites/storageperf/storage_perf_utils.go
Sometimes, there is a race condition where the linux startup script to install fio does not complete before the test runs.
This causes the fio command to fail because it was not found. To fix this, wait until fio is installed.
=> Wait for fio to finish installing on linux

imagetest/test_suites/storageperf/iops_read_test.go, imagetest/test_suites/storageperf/iops_write_test.go, imagetest/test_suites/storageperf/setup.go, imagetest/test_suites/storageperf/storage_perf_utils.go
The IOPS benchmarks are defined as a float64, but they might not print correctly as part of the %f format keyword in logf and printf.
Instead, convert it to a string and use %s.
Note that this change might cause some storageperf tests to "fail" to meet performance thresholds because float values are now rendering correctly.
In some of these situations, such as c3-hyperdisk extreme random read, the discrepancy between manual testing values and automated testing values would need to be investigated in a future fix.
=> Print string instead of float

imagetest/test_suites/storageperf/iops_read_test.go, imagetest/test_suites/storageperf/iops_write_test.go, imagetest/test_suites/storageperf/storage_perf_utils.go
In the error log for test failures, print the machine type. For example, we would know if the failure was pd balanced for n1-standard-64 based on the error message vm name.
=> Print vm name for failing tests

concourse/pipelines/guest-package-build.jsonnet, imagetest/fixtures.go, imagetest/go.mod, imagetest/go.sum, imagetest/test_suites/README.md, imagetest/test_suites/oslogin/oslogin_test.go, imagetest/test_suites/oslogin/oslogin_utils.go, imagetest/test_suites/oslogin/setup.go, imagetest/test_suites/oslogin/ssh_test.go, imagetest/utils/test_utils.go
Also move from using the deprecated `ioutil` to using the `os` package for reading files.
The tests include
- Checking 2FA enabled and appropriate headers related to turning 2FA on.
- SSH-ing with OSLogin enabled works as intended
- TODO: SSH-ing with OSLogin 2FA enabled works as intended.
=> OsLogin Tests

imagetest/test_suites/imageboot/setup.go
http://localhost:8080/teams/guestos/pipelines/windows-image-build-mbr/jobs/publish-to-testing-windows-server-2012-r2-dc-bios/builds/3
=> Require the UEFI_COMPATIBLE flag for secure boot tests

imagetest/test_suites/storageperf/iops_read_test.go, imagetest/test_suites/storageperf/iops_write_test.go, imagetest/test_suites/storageperf/storage_perf_utils.go
Most commonly, sometimes on startup the sles instances might have a zypper process running, leading to an exit code 7 when running "zypper install." Other errors such as 104 (repository not available) or 106 (zypper refreshing repositories failed) sometimes happen as well, indicating a temporary backend error.
This is not actionable by PD or teams working on disk performance and should not fail the test, so skipping the specific test case run is the proposed solution. I'm open to other suggestions for zypper backend errors. 
Also, use the full size of the mounted disk for benchmarking
https://cloud.google.com/compute/docs/disks/benchmarking-pd-performance#raw-disk
=> Skip tests on zypper install issue

imagetest/test_suites/networkperf/gvnic_test.go, imagetest/test_suites/networkperf/startupscripts/netclient_startup.sh, imagetest/test_suites/networkperf/startupscripts/netserver_startup.sh
When the number of parallel threads is high, the images seem to reject them for some reason. This is a patchwork fix so the tests don't constantly time out.
=> Reduce Parallel Thread Count for Network Performance Tests for SUSE Images.

imagetest/Dockerfile, imagetest/local_build.sh
This is required to avoid some issues with glibc versioning on certain OS. This won't affect building via the dockerfile, but it will fix some edge case failures when building without the dockerfile.
/cc @zmarano @jjerger @koln67 @drewhli
=> Move CGO_ENABLED declaration from Dockerfile to local_build.sh

imagetest/test_suites/cvm/cvm_test.go
Spawning a shell to grep through output before parsing strings again in go is causing some false negatives when there is an error from grep unrelated to presence of the module's message (this happens on ubunutu-2004-lts).
/cc @zmarano @koln67 @drewhli @jjerger
=> Search dmesg output in go for CVM tests and deduplicate test code

packagebuild/common.sh
We found an issue[1] in golang's path/filepath stdlib impacting the build of at least osconfig (potentially others). The bug was fixed and will potentially be available in 1.31.5, we'll get it update whenever it's released.
[1] - https://github.com/golang/go/issues/64028
=> package build: downgrade golang to 1.21.3

container_images/cleanerupper/go-cleanerupper/cleanerupper.go, container_images/cleanerupper/go-cleanerupper/cleanerupper_test.go, imagetest/go.mod, imagetest/go.sum, imagetest/testworkflow.go, imagetest/testworkflow_test.go
Change WorkflowPolicy to match the workflow ID in both name and description.
The two resources we are having problems with are instances and networks so this is limited to that (plus disks to clean up disks left behind by the instances)
/cc @zmarano @jjerger @koln67 @drewhli
=> Call cleanerupper after running a CIT suite to clean up any resources left behind by Daisy.

concourse/pipelines/container-build.jsonnet, imagetest/Dockerfile, imagetest/README.md, imagetest/local_build.sh
1) CGO_ENABLED should be exported to be picked up by child processes
2) The dockerfile should be built relative to the root directory to allowed the imagetest go.mod to find cleanerupper nested in the directory above it
3) Correct the concourse pipeline [failing](http://localhost:8080/teams/guestos/pipelines/container-build/jobs/build-cloud-image-tests/builds/472) because of issue 2 to build with the new method.
`local_build.sh` is unaffected by these changes.
/cc @zmarano @jjerger @koln67 @drewhli
=> Fix various issues with dockerfile builds

concourse/pipelines/guest-package-build.jsonnet
The images are not public any more, we should use the private resource type and use google auth.
=> package build: use private image for concourse metrics

concourse/tasks/render-templates.yaml
Instead of using registry-images-private alias use the original name.
=> render-templates: use registry-image-forked

concourse/tasks/render-templates.yaml
Instead of using registry-images-forked use the upstream one.
=> render-templates: use registry-image

concourse/pipelines/pipeline-set-pipeline.yaml, concourse/tasks/render-templates.yaml
Add the registry-image-private resource type as a resource and use it instead of registry-image.
=> pipeline-set: use registry-image-private

concourse/pipelines/guest-package-build.jsonnet
The resource type registry-image-forked doesn't need google_auth.
=> package build: don't use google_auth for resource type

imagetest/Dockerfile, imagetest/go.mod
`slices` is go 1.21 only, but we should keep up to date anyway
/cc @zmarano @jjerger @koln67 @drewhli 
http://localhost:8080/teams/guestos/pipelines/container-build/jobs/build-cloud-image-tests/builds/483
=> Bump CIT go version from 1.20 to 1.21

imagetest/test_suites/networkperf/startupscripts/windows_clientstartup.ps1, imagetest/test_suites/networkperf/startupscripts/windows_serverstartup.ps1
The daisy logs on windows for the networkperf test suite always logs that the windows startup script completes successfully. In a few of these runs, there is a 404 error when trying to get test results.
Adding a try catch will add an error message to the logs when the 404 error occurs, so we know which command did not run successfully.
In the future, @drewhli will add more detailed debugging for iperf failing to complete successfully.
=> Add try catch to ps1 networkperf startup scripts

concourse/pipelines/artifact-releaser-test.jsonnet, concourse/pipelines/partner-image-validations.jsonnet, concourse/templates/common.libsonnet
Notably, the ARLE test pipeline is currently failing because it's not defined there.
=> Define registry-image-private in a template and import it across pipelines that need it

imagetest/test_suites/disk/setup.go
/cc @jjerger @drewhli @koln67 @elicriffield
=> Require GVNIC for udev tests, required for machine families that support nvme

imagetest/test_suites/guestagent/snapshot_test.go
=> Don't fail snapshot test when the agent configuration doesn't exist yet

imagetest/test_suites/metadata/shutdown_script_test.go, imagetest/test_suites/metadata/startup_script_test.go
dnf and yum don't have a command that forces a reinstall or an upgrade
Also swapped the argument order for zypper, newer version require the --force flag after the install command
/cc @koln67 @drewhli
=> Add a fallback command to retry reinstalling guest agent during startup/shutdown script testing

imagetest/test_suites/guestagent/telemetry_test.go
This should only happen when the agent is too old to support telemetry.
/cc @elicriffield @drewhli
=> Skip telemetry testing when the agent never mentions it.

imagetest/cmd/manager/main.go, imagetest/local_build.sh, imagetest/testworkflow.go, imagetest/testworkflow_test.go
Necessary to run CIT in staging. I also noticed the `local_build.sh` doesn't exit with a non-zero code when I broke the wrapper or the manager, so I fixed that.
/cc @koln67 @jjerger
=> Allow override compute client endpoint

concourse/pipelines/linux-image-build.jsonnet
We don't need new images to continue testing the existing ones. The evidence looks pretty conclusive in favor of this being the culprit already.
/hold
=> Disable centos-7-predictable-nic-builds

imagetest/test_suites/packagevalidation/package_test.go
We are transitioning images from google-cloud-sdk to google-cloud-cli
however rocky linux 8 optimized for arm hasn't yet finished the transition.
=> package_test: we haven't published a rocky 8 for arm with google-cloud-cli

imagetest/test_suites/packagevalidation/package_test.go
Agent is released now and it breaks staging
This reverts commit f146c18299b6744443ba93432476e2c361939b50.
/hold
=> Revert "package_test: we haven't published a rocky 8 for arm with google-cloud-cli (#1006)"

imagetest/test_suites/security/image_security_test.go
This comes up on Ubuntu 16.*
/cc @zmarano @elicriffield
=> Remove header manually when an OS is too old to support the -H flag in ss

imagetest/test_suites/network/setup.go
Guest agent doesn't support alias IP ranges on windows.
/cc @elicriffield @drewhli
=> Skip running alias ip tests on windows, skip creating the multinic vm at all when there's nothing to test

imagetest/test_suites/packagevalidation/package_test.go, imagetest/test_suites/storageperf/setup.go, imagetest/test_suites/storageperf/storage_perf_utils.go
https://cloud.google.com/compute/docs/disks/performance#zonal
PD balanced disks can only provide 6 iops per GB.
This change calculates the approximate disk size needed to reach the hard coded performance limit and allocates a disk of that size.
=> Pdbalancefill

imagetest/testworkflow.go
When doing local testing, if the instance is deleted after ctrl + z and has a mount disk, the mount disk is not deleted by default.
This helps clean up resources when doing manual runs.
=> Auto delete mounted disks

imagetest/test_suites/metadata/metadata_utils.go, imagetest/test_suites/metadata/shutdown_script_test.go, imagetest/test_suites/metadata/startup_script_test.go
Necessary to avoid attempting to reinstall a pkg removed from repos on distros with apt.
This was getting to be a lot of duplicated logic so I abstracted the logic into a general case. I considered putting this until test_utils but no other test suite needs this AFAIK so I left it in metadata.
=> Add a prep command for guest agent reinstallation

imagetest/test_suites/storageperf/iops_read_test.go, imagetest/test_suites/storageperf/iops_write_test.go, imagetest/test_suites/storageperf/setup.go, imagetest/test_suites/storageperf/storage_perf_utils.go
LSSDs present on the machine are collected into a raid array as directed in our public documentation
I abstracted installFioLinux to install any package and used that to install mdadm for the array setup, then added some logic to install libnuma-dev on ubuntu 1604 and 1804 since this came up just now and I already wrote that abstraction
Added performance targets for LSSDs
Added some logic to determine "disk class" eg. PD, hyperdisk, or LSSD and reworked logic to return fio options based off that
getMountDiskSize returns 0 for LSSD so that it doesn't wait for quota it doesn't need
Test setup logic just checks of diskType is lssd and skips adding a secondary disk if so.
/cc @koln67 @zmarano
=> Add LSSD support and cases to storageperf

imagetest/testworkflow.go
Should be enabled be default for boot disks but I think some of the secondary disks are getting left behind.
/cc @drewhli @zmarano
=> Autodelete all disks created for testvms

imagetest/test_suites/hotattach/setup.go
/cc @drewhli @koln67 
I don't remember if there's a reason we're not doing this.
=> Run hotattach on whatever machine type the rest of the suite is run on

concourse/pipelines/guest-package-build.jsonnet, concourse/pipelines/linux-image-build.jsonnet, concourse/pipelines/partner-image-validations.jsonnet, concourse/tasks/image-test-args.yaml
stop specifying machine type for arm images, no longer 
necessary switch gcp-guest => compute-image-test-pool-001
correct a few typos in argument names
/cc @drewhli @elicriffield
=> Update usage of CIT in concourse pipelines

imagetest/test_suites/packagevalidation/package_test.go
Everything in both staging and prod should have google-cloud-cli at this point
=> Remove google-cloud-sdk as a substitute for google-cloud-cli

imagetest/testworkflow.go
/cc @drewhli @zmarano 
This is extremely ugly (O(N^3) for the triply nested loop) but there is no direct link between a VM and a disk and finding the link between disk and attachedDisk is O(N^2) because of the way daisy stores this data. To make this prettier and more efficient we could either break the daisy API by switching CreateDisks to a map (will cause problems for anyone using the latest version of the CLI tool to import a pre-written json workflow) or we could modify CIT or daisy to better parse and handle failures from the compute API.
Either way these are long(er) term solutions and we should (imo) do this in the interim to make things work for these machine types right now.
=> Switch disk types to hyperdisk extreme for machine types that don't support PD

concourse/pipelines/guest-package-build.jsonnet, concourse/tasks/image-test-args.yaml
Need to sort out GCS permission issues first, and the service accounts here are kind of a maze
=> Switch compute-image-test-pool-001 back to gcp-guest in concourse pipelines

imagetest/test_suites/oslogin/README.md, imagetest/test_suites/oslogin/setup.go, imagetest/test_suites/oslogin/ssh_test.go
This should help with reducing the overall flakiness everywhere.
=> Add 4 more users for each OSLogin 2FA SSH test

imagetest/testworkflow.go
Previous code was only cleaning up after test workflows on successful runs
=> Clean test workflows even on failure

concourse/pipelines/guest-package-build.jsonnet
We are trying to use images from one project while we are pushing it to the other, this change brings it back to consistency.
=> Move derivative image build back to gcp-guest

imagetest/test_suites/network/dhcp_test.go
The tests need to be adjusted to the new guest-agent network manager interface implementation, all the exceptions must be addressed (i.e. not all systems will have dhclient processes for both primary and secondary nics).
=> Permanently disable DHCP tests for debian-10 and debian-11

imagetest/fixtures_test.go, imagetest/go.mod, imagetest/go.sum, imagetest/test_suites/networkperf/setup.go
Partial fix for test grid failures [here](https://testgrid.k8s.io/googleoss-gcp-guest#cit-periodics-performance), other component of the fix is [here](https://github.com/GoogleCloudPlatform/compute-daisy/pull/39)
=> Test setting subnetwork region and take base name of region url

imagetest/test_suites/licensevalidation/setup.go
=> Integrate rhel and rhel-byos licensevalidation rules, use image name rather than family name

concourse/pipelines/linux-image-build.jsonnet, concourse/pipelines/windows-image-build-standard.jsonnet
I also dropped the serial_groups tags (this is a no-op, these don't work cross-pipeline anyway)
/cc @zmarano @elicriffield
=> Exclude 4th gen machine type testing from release pipelines

imagetest/test_suites/networkperf/setup.go
Fixes failures here: https://oss.gprow.dev/view/gs/oss-prow/logs/cit-periodics-performance/1757725494280720384
/cc @drewhli @koln67 
successful run (with up to 3rd gen machines):
```
arate@acrate-p1g4 ~ > cit-local -timeout 10m -project compute-image-test-pool-001 -filter networkperf -networkperf_test_filter=[a-z][0-3] -images projects/debian-cloud/global/images/family/debian-12,projects/debian-cloud/global/images/family/debian-12-arm64
2024/02/14 10:49:31 Running in project compute-image-test-pool-001 zone us-central1-a. Tests will run in projects: [compute-image-test-pool-001]
2024/02/14 10:49:31 using -filter networkperf
2024/02/14 10:49:31 Add test workflow for test networkperf on image projects/debian-cloud/global/images/family/debian-12
2024/02/14 10:49:35 Add test workflow for test …
```
=> Take base name of region in all cases for networkperf

concourse/pipelines/guest-package-build.jsonnet, imagetest/test_suites/licensevalidation/setup.go
Licensevalidation is validating the image metadata, not the behavior, so this is completely unaffected by guest packages. Building the guest package derivative images in a way that looks more like how we build them for prod would make this work as well, but doesn't bring any benefit to guest package testing and this is simpler.
/cc @drewhli @dorileo 
/hold
=> Fix and enable linux license validation, exclude from guest package integration test pipelines

imagetest/test_suites/guestagent/telemetry_test.go
/cc @jjerger @koln67 
My last attempt still line wrapped in some situations. This just dumps raw output with no formatting, so no more parsing failures.
=> Avoid line breaks when getting agent output on windows

concourse/pipelines/linux-image-build.jsonnet
Think I got it figured out. `jsonnet concourse/pipelines/linux-image-build.jsonnet` output: https://gist.github.com/a-crate/a13d4ad6bf462bf61d6d1e053a81c3a7
/assign @bkatyl
=> Add rhel c3m image group that skips CIT

concourse/pipelines/guest-package-build.jsonnet
Template for artifact registry package upload tasks, which will eventually replace the current cloud rapture package upload tasks.
No instances of this task are being called yet, until a follow up PR.
=> Artifact Registry task template

imagetest/test_suites/metadata/shutdown_script_test.go, imagetest/test_suites/packagevalidation/gce_sysprep_test.go, imagetest/test_suites/packagevalidation/package_test.go
Stop checking for google-cloud-cli on Ubuntu 1604
Stop checking shutdown script execution during agent reinstall
Stop checking osconfig agent status on older gcesysprep versions (I also bumped acceptable record count to 200, there is some flakiness in this test)
All of these issues have been raised with owners, either internally or with partners.
=> Stop checking for known issues in CIT

imagetest/cmd/wrapper/main.go
While I was looking into recent timeouts I noticed some of them were failing to set guest attributes. This this add a three attempt retry with a small backoff after each attempt. Tested locally and both tests that reboot and tests that don't reboot work OK.
/cc @koln67
=> Retry setting guest attributes in the cit manager up to three times

imagetest/test_suites/disk/setup.go
/cc @elicriffield @drewhli 
I think this should be a less contested resource than c3. Unfortunately there is no clean way to just say "give me a 3rd gen machine type," we still have to specify one with minimum cpu platforms, and the API won't autoselect one if I just specify an nvme interface for the attached disk.
=> Switch to C3D for X86_64 disk naming tests

concourse/pipelines/partner-image-validations.jsonnet
CIT for partner images is much more reliable now, a lot of test failures are the suites attempting to use the resource before it's ready or flaky zone resource pool exhaustion stuff.
example: http://localhost:8080/teams/guestos/pipelines/partner-image-validations/jobs/ubuntu-pro-2004-lts-arm64/builds/22 retrying this would likely pass on the second attempt
/cc @zmarano @drewhli
=> Retry partner image validation three times

imagetest/testworkflow.go
/cc @zmarano @drewhli 
not sure why this was initially disabled, the PR that disabled it doesn't address it. It's making debugging potential daisy bugs that show up in testgrids a bit difficult.
=> Send daisy logs to GCS

imagetest/cmd/wrapper/main.go, imagetest/fixtures.go, imagetest/fixtures_test.go, imagetest/go.mod, imagetest/go.sum, imagetest/test_suites/imageboot/setup.go, imagetest/test_suites/imageboot/suspend_resume_test.go
Waiting on GoogleCloudPlatform/compute-daisy#41
/hold
My local testing shows far less (none so far) flakes on this implementation. I moved the watching for suspension and the resume call to the CIT framework and out of a secondary VM, and close and reopend the connection the GCS before and after executing the test binary so that whatever tests do to the VM has less effect on the test wrapper.
=> Improve suspend testing reliability

imagetest/cmd/manager/main.go
Trying to configure testgrid to consider a run as passing if <1.5% of tests are failing, but it will always consider failing if the test process exits with non-zero exit code, regardless of failure threshold
=> add set_exit_status flag

imagetest/test_suites/metadata/metadata_utils.go
We were not actually disabling the other repos but "forcing to enable" the repo of interest.
=> metadata: do actually disable other repos

imagetest/test_suites/metadata/metadata_utils.go, imagetest/test_suites/metadata/shutdown_script_test.go, imagetest/test_suites/metadata/startup_script_test.go
The repository names for EL distros are pretty stable for guest environment packages, this change fixes it to the known and stable name.
=> metadata: fix the dnf and yum repo restriction

imagetest/test_suites/network/mtu_test.go
Some sysprep versions don't have commit d78b5cf from compute-image-windows, needed to set MTU correctly on some subinterfaces.
/cc @jjerger @koln67
=> Skip MTU test on old sysprep versions

imagetest/test_suites/packagevalidation/package_test.go
COS does not ship gcloud and gsutil utilities.
=> Update package_test.go to skip COS in TestStandardPrograms

imagetest/test_suites/metadata/metadata_utils.go, imagetest/test_suites/metadata/shutdown_script_test.go, imagetest/test_suites/metadata/startup_script_test.go
Fix for metadata-sles-12.TestStartupScripts failures.
Waiting forever would be ideal but older versions of libzypp are bugged. Since we're waiting for such a long time, plumb a context through reinstallGuestAgent so that we kill the process when the test times out.
/cc @drewhli @koln67
=> Wait for zypper lock for a long time

imagetest/junit.go, imagetest/test_suites/metadata/shutdown_script_test.go, imagetest/testworkflow.go
This provides a clearer signal for alerting on. It also makes which tests are and aren't run clearer to humans reading results.
Here is an example of the problem: https://testgrid.k8s.io/googleoss-gcp-guest#cit-periodics&include-filter-by-regex=metadata-sles-12
When a test encounters a workflow failure every test in the suite is marked as failing. Then later when the results are executing correctly, if one of those tests isn't run on an image there are no new results. This means alerts that fire on metadata-sles-12.TestShutDownScriptTime will fire forever because the test doesn't have new results after the failures. 
This also provides a clearer signal to humans when tests aren't being executed (intentionally or unintentionally) like the issue I just discovered that TestShutdownScriptTime …
=> Mark tests not skipped or run as disabled

imagetest/test_suites/network/setup.go
COS has ip_alias=False in our instance_config file, we can skip the alias tests on COS.
=> Update setup.go to skip alias tests for COS images

imagetest/fixtures.go, imagetest/test_suites/cvm/setup.go, imagetest/test_suites/disk/setup.go, imagetest/test_suites/guestagent/setup.go, imagetest/test_suites/hotattach/setup.go, imagetest/test_suites/metadata/setup.go, imagetest/test_suites/network/setup.go, imagetest/test_suites/networkperf/setup.go, imagetest/test_suites/packagevalidation/setup.go, imagetest/test_suites/security/setup.go, imagetest/test_suites/shapevalidation/setup.go, imagetest/test_suites/sql/setup.go, imagetest/test_suites/ssh/setup.go, imagetest/test_suites/storageperf/setup.go, imagetest/test_suites/storageperf/storage_perf_utils.go, imagetest/testworkflow.go
The utils.GetRealVMName relies on this convention even though it's completely unenforced, meaning it doesn't work unless the test author complied. This enforces it. Also use a proper temp dir for ssh test setup in the manager.
/cc @drewhli @koln67
=> Enforce a lack of dashes in testworkflow vm names.

imagetest/test_suites/metadata/setup.go, imagetest/test_suites/metadata/shutdown_script_test.go
They don't work now and as far as I can tell they never have, but this way we have a reminder that they are broken.
=> Delete shutdown script time tests

packagebuild/daisy_startupscript_deb.sh
It seems the repository lost its Release file, for now we are disabling the repository as we don't need them for package builds.
=> package build: disable debian-10 backport repos

imagetest/test_suites/guestagent/windows_password_test.go
I think this should reduce flakes due to powershell handling special characters differently in double quotes.
/cc @jjerger @koln67
=> Use single quote string in windows password test

imagetest/cleanerupper/cleanerupper.go, imagetest/cleanerupper/cleanerupper_test.go
Match only the workflow name. This will allow this hook to clean up things created in test binaries since they usually don't set a description but reuse the workflow id.
=> Make CIT's post-testworkflow cleanerupper more aggressive

imagetest/test_suites/guestagent/windows_password_test.go, imagetest/test_suites/packagevalidation/windows_version_test.go, imagetest/test_suites/security/image_security_test.go, imagetest/test_suites/winrm/setup.go, imagetest/utils/test_utils.go
Surface unexpected service states more clearly
Wait longer for windows password reset test
Allow sql server port listeners and idle listeners on dynamic ports
Make sure passwords meet complexity requirements in winrm test
/cc @koln67 @drewhli
=> Fix issues with CIT in windows

imagetest/test_suites/winrm/setup.go, imagetest/utils/test_utils.go
Fixes this failure: https://console.cloud.google.com/storage/browser/_details/gcp-guest-cloud-test-outputs/2024-04-25T10:52:30Z/winrm/windows-server-2016-dc-core-v20240415/daisy-winrm-20240425-13:07:14-716br/logs/server-winrm-716br-serial-port1.log;tab=live_object
=> Allow 14 char passwords and use one in winrm

concourse/pipelines/guest-package-build.jsonnet
This PR pairs with this PR in compute-image-tools: https://github.com/GoogleCloudPlatform/compute-image-tools/pull/2309.
This PR does the following:
- Creates a new buildpackageimagetaskcos. This is similar to buildpackageimagetask but has unique parameter sets and invokes install_package_cos.wf.json.
- Adds a call to the buildpackageimagetaskcos for COS 113. In the future we will expand this to more milestones, but we are starting with one for simplicity. This passes in the parameters for the task (like source name, dest name, package version, and cos branch).
- Adds cos as a distro to test against guest-agent.
Notes:
- We might need to grant permissions to service accounts to make this work so permission-related issues are expected.
- Need to reconsider passing in the full path for …
=> Add COS configs to the concourse pipeline

concourse/pipelines/linux-image-build.jsonnet
=> Require n4 shapevalidation for linux image releases

concourse/pipelines/guest-package-build.jsonnet
The preloading script only needs the image family name, the full path is not needed. This is because cos-customizer (how preloading is implemented) doesn't take the full path.
The preloading script will get the path from the other args passed in (for ex: _BASE_IMAGE_PROJECT in compute-image-tools).
=> Pass in image family (not full path to image family)

concourse/pipelines/windows-image-build-staging.jsonnet, concourse/pipelines/windows-image-build.jsonnet
Probably to be moved to prod when we can fully automate the publish process. For now, we don't want to run the tests on publish-to-prod as thats the final human step to send it to ARLE, and we should be blocking on publish-to-testing if CIT fails.
=> Update CIT to run only during testing publish for Windows

concourse/pipelines/guest-package-build.jsonnet
Since the "stable" ref name's been historicaly used for purposes of marking the latest stable release we are kind of limited of using it, for the purpose of stable releases we are using the topic-stable name.
=> Move guest-agent stable branch to topic-stable.

concourse/pipelines/guest-package-build.jsonnet
After looking at where the file is stored in GCS, fix the typo
=> Fix GCS path for apt transport

concourse/pipelines/guest-package-build.jsonnet
Similar to the bucket path, the sbom path had a typo
=> Fix apt transport sbom path

concourse/tasks/generate-hash.yaml
sha256sum prints the hash, then a space, then the file name. We only want the hash so drop the file name.
=> Only print the hash and not the file name

concourse/pipelines/guest-package-build.jsonnet
In order to add support for more COS milestones, patches will be applied from the master branch, see PR: https://github.com/GoogleCloudPlatform/compute-image-tools/pull/2323
This means that overlay branch arg is no longer necessary and can be removed from all occurrences.
CCing @a-crate, @zmarano.
=> Add support for COS milestones (+109, +105)

concourse/pipelines/linux-image-build.jsonnet, concourse/pipelines/windows-image-build.jsonnet, concourse/templates/arle.libsonnet
The sha256 calculation is moving to the daisy workflows.
In the pubsub message handling, we will make a change so that we do not accept the sha sum directly, but instead accept a file which has the sha sum. Since we're deprecating image_sha256_hash in the pubsub message soon, remove it from the concourse calls.
=> Remove calls to sha256 sum

concourse/pipelines/linux-image-build.jsonnet, concourse/pipelines/windows-image-build.jsonnet, concourse/tasks/generate-build-id-shasum.yaml, concourse/templates/arle.libsonnet, concourse/templates/common.libsonnet, concourse/templates/daisy.libsonnet
Follow up to https://github.com/GoogleCloudPlatform/compute-image-tools/pull/2328, don't merge this until that is merged.
This change would pass in the sha sum text file to ARLE and other workflows in the same way the sbom file is passed in.
=> Add support for the sbom shasum text file resource

concourse/pipelines/guest-package-build.jsonnet
Stop testing on RHEL/Centos 7 and Debian 10. Start testing on Debian 12 where that wasn't already happening. Stop uploading packages to debian 10 and centos 7 repositories.
/hold
/cc @ChaitanyaKulkarni28 @zmarano
=> Update guest package release pipelines

concourse/pipelines/windows-image-build-mbr.jsonnet, concourse/pipelines/windows-image-build-staging.jsonnet, concourse/pipelines/windows-image-build-standard.jsonnet, concourse/pipelines/windows-image-build.jsonnet
Dropping SQL Server 2014 as well as remaining 2012 references from windows build pipelines
=> Removing deprecated 2014 and 2012 references from builds

concourse/pipelines/linux-image-build.jsonnet
Deprecated last week; no backport maintainer
=> Remove Debian 11 arm from concourse build

concourse/pipelines/container-build.jsonnet
Half the workers currently have a bad image cached.
=> Force latest version to clear cache

concourse/pipelines/linux-image-build.jsonnet, concourse/pipelines/windows-image-build.jsonnet
Use "filter" instead of "exclude": this change uses "filter" for all the test suites which were not previously covered by "exclude."
=> Include test suites instead of excluding

concourse/pipelines/linux-image-build.jsonnet, concourse/pipelines/windows-image-build-mbr.jsonnet, concourse/pipelines/windows-image-build-staging.jsonnet, concourse/pipelines/windows-image-build-standard.jsonnet, concourse/pipelines/windows-image-build.jsonnet
This avoids ^(cvm)|(network)|(...)$ matching networkperf
/cc @koln67
=> Use a single capturing group in image build filters

container_images/gointegtest/common.sh, packagebuild/common.sh
Due to some vulnerabilities with 1.22 we are bumping the toolchain we use both to build packages and the container image to 1.23.2.
=> Bump package build and container build's golang version

concourse/pipelines/guest-package-build.jsonnet
The arm64 os build isn't enabled for apt transport
=> Add arm64 package build for apt-transport

container_images/gobuild/Dockerfile, container_images/gocheck/Dockerfile, container_images/gotest/Dockerfile
In order to be able to generate pb.go files during build time we need to have installed the protobuffer compiler and the go-grpc generator.
google-guest-agent repository is not checking in generated code but relying on its build system to generate it during build time, prow nodes must have the required tooling to do so.
=> container-images: install protobuffer tooling.

concourse/pipelines/guest-package-build.jsonnet
Concourse will try to interpolate variables even if they are not set in that case if the variable is not set concourse will fail with an "no such variable" kind of error - this change fixes that.
Additionally originally we set extra_repo to the wrong build pipeline, we set it to guest-agent-dev when we should have set it to guest-agent.
=> package build: selectively pass daisy args & pipeline shift

concourse/pipelines/guest-package-build.jsonnet
Previous was an implicit include, which made it unnecessarily pick up new test suites unless explicitly excluded.
=> Switch CIT package tests to explicit include list

packagebuild/common.sh, packagebuild/daisy_startupscript_rpm.sh
Introduce the required bits to honor extra source code when building rpm packages - this supports packaging that require more than a single source code such as guest-agent that is building plugin-manager side-by-side.
=> rpm build: build package with extra source

packagebuild/daisy_startupscript_goo.sh, packagebuild/test_build.sh
[PR](https://github.com/GoogleCloudPlatform/guest-agent/pull/456) added support for including Plugin Manager in guest-agent package. Update packaging scripts to include extra repos and install protoc/make tools required by new extra repo
=> Add extra repo support in googet packaging startup script

packagebuild/daisy_startupscript_rpm.sh
As git_checkout() is not popping from the checkout dir we were setting the root directory inside the package's source code (not the expected), for that then we set the variable before the first git_checkout() call.
Additionally we are setting -e and -x flags so the it fails early and also prints the script tracing.
=> rpmbuild: properly set root dir and enable tracing

packagebuild/common.sh, packagebuild/daisy_startupscript_rpm.sh
We are missing make as a build dep and we were installing x86 protoc regardless the running system's architecture, this change fixes both.
=> rpm build: install make and add arm64 support

concourse/pipelines/guest-package-build.jsonnet
Add package as an explicit parameter where applicable, otherwise hardcode it for the job
Fixes http://localhost:8080/teams/guestos/pipelines/guest-package-build/jobs/build-guest-oslogin/builds/106
http://localhost:8080/teams/guestos/pipelines/guest-package-build/jobs/build-guest-configs/builds/54
=> Fix buildid name generation

concourse/pipelines/guest-package-build.jsonnet
Instead of using variable interpolation use a template object concatenation and fix the generate-build-id interpolation panic.
=> package build: fix generate-build-id

concourse/pipelines/guest-package-build.jsonnet
=> Fix derivative image naming for rocky-linux-9 in guest-configs

concourse/pipelines/linux-image-build.jsonnet, concourse/pipelines/partner-image-validations.jsonnet
Removed noop tests from linux image builds and added missing tests to partner image validation
/cc @jjerger @bkatyl
=> Update linux image build test filter, switch partner images to filter

concourse/pipelines/linux-image-build.jsonnet
PR https://github.com/GoogleCloudPlatform/compute-image-tools/pull/2392 moved rocky builds from `accelerator_images` to `enterprise_linux` update workflow_dir in pipeline as well
/cc @a-crate @jjerger
=> Update work_dir for accelerator image builds

concourse/pipelines/linux-image-build.jsonnet
Updates based on [PR](https://github.com/GoogleCloudPlatform/compute-image-tools/pull/2398), builds are failing with - `no such file or directory`
/cc @a-crate @jjerger
=> Switch rocky-8 from 550 to latest

concourse/pipelines/windows-image-build.jsonnet
- Adding SQL Server on 2025
- Removing SQL Preview
- SQL express on 2022/2025
- Extending CIT test execution to test on c3 for hw related tests
=> SQL on 2025, cleanup, cit on c3

concourse/pipelines/linux-image-build-dev.jsonnet, concourse/pipelines/linux-image-build.jsonnet, concourse/templates/common.libsonnet
Define the default linux image build CIT filter in a central location. Allow passing extra args. Skip licensevalidation in rocky accelerator pipelines (temporarily, while it's publishing to the preview project). Run accelerator tests and use the alpha API for accelerator images.
/cc
/hold
=> Update linux-image-build and linux-image-build-dev cit invocations

concourse/pipelines/windows-image-build.jsonnet
- Some test runs are taking just over 45 minutes which causes a retry.
=> Change the timeout for Windows CIT tests run in the build pipeline to 60m.

concourse/pipelines/linux-image-build.jsonnet
The reservation was deleted and recreated. guestos-a3u-gsc no longer exists
/hold
/cc @jjerger @zmarano
=> Update A3Ultra reservation name

concourse/pipelines/windows-image-build-staging.jsonnet
Incorrectly passed in values in previous config, so it wasn't using workload ID
=> Update windows staging pipeline to use forked registry image

concourse/pipelines/linux-image-build-dev.jsonnet, concourse/pipelines/linux-image-build.jsonnet
=> Add rocky linux accelerator images with nvidia 550 to the dev pipeline

concourse/pipelines/guest-package-build.jsonnet
Without forcing fetching tags we can't generate a new version on the same day.
=> guest package build: force fetching tags

concourse/pipelines/guest-package-build.jsonnet
Similar to what we do for guest-agent this change introduces a stable build pipeline so we can have a roll-forward package at release time.
=> oslogin: add stable build pipeline

concourse/pipelines/guest-package-build.jsonnet
The build pipeline is failing to upload images due a daisy image name size validation (max of 64 chars) for some images. This change shortens the word stable to stbl so image names can comply with the validation.
=> oslogin: shorten stable so image names are under 64 chars

concourse/pipelines/linux-image-build.jsonnet
Previously the machine shape was hard coded into the test suite. We want to make it generic, so the first step is to pass in the machine shape argument.
=> Use the a3 ultra machine shape by default

concourse/pipelines/accelerator-image-build.jsonnet
Removes extra suffixes that aren't used (byos/sap); adds 570
=> Fix isopath trimming for accelerator builds

concourse/pipelines/accelerator-image-build.jsonnet
The shapes tested don't make sense for this; test case is covered in the prepublish test done during publish to testing
=> Remove prepublish tests from accelerator pipeline

concourse/pipelines/accelerator-image-build.jsonnet
The lack of hardware availability requires the tests to not overlap. Setting 1 hour gaps between the publish tasks so that they can run without overlapping hardware-limited test suites.
=> Stagger Accelerator CIT Test publish tasks

concourse/pipelines/guest-package-build.jsonnet
T2A_CPUS quota is limited and builds consistently fail with resource exhaustion error. Update to use c4a which is newer and has higher quota
=> Change machine type to use c4a for arm builds

container_images/cleanerupper/main.go
This is to more easily track the timeline of a cleanerupper run for debugging purposes.
/cc @jjerger 
/hold
=> Add time to cleanerupper log messages

concourse/pipelines/guest-package-dev-build.jsonnet, packagebuild/workflows/build_deb13.wf.json
Switches package build image sources to a bootstrap image I think will do the trick.
=> Update Debian13 image paths for testing

concourse/pipelines/guest-package-dev-build.jsonnet
The others arent being built so need to be removed for now.
=> Scope down oslogin arm image tests to deb13

concourse/pipelines/guest-package-dev-build.jsonnet
We need the package to complete and intend to test it later. For now, disable the tests which are failing for an unrelated reason
=> Drop guestconfigs tests from Debian13 test build

packagebuild/daisy_startupscript_rpm.sh
Building in 10 requires gcc now; added version check to install gcc for version 10. Required change to logic setting VERSION_ID as it would truncate 2 digit version numbers. Tested with CentOS 8, 9, 10, all succeed to build guest agent in testing.
=> Update rhel package build script

concourse/pipelines/guest-package-dev-build.jsonnet
The default is currently still set to Debian 11 for the worker images. We should update this in the future, but for now let's be explicit in using the Debian 12 worker to get things running.
I plan to test using Debian 12 as a default in all builds after discovering this, but let's not potentially break existing builds by moving default workers.
=> Use Debian 12 worker in Deb13/RHEL10 package build

packagebuild/workflows/build_goo.wf.json
Makes it consistent with other worfklows using debian source images and should fix 
`E: The repository 'https://deb.debian.org/debian bullseye-backports Release' no longer has a Release file.`
=> Update source image to use in package build workflow

concourse/pipelines/guest-package-build.jsonnet
This is copying the setup we have for the guest agent builds. Currently Debian 11 images are facing an issue where `apt update` is failing due to one of the backports repos being turned down. This is thus causing package builds to fail.
Also remove the obsolete Debian 10 upload task.
=> Stop building on Debian 11 for guest configs, reuse Debian 12's instead

concourse/pipelines/guest-package-build.jsonnet
Package builds are failing with error `projects/rhel-sap-cloud/global/images/family/rhel-9-6-sap-ha does not exist`
=> Remove rhel-9-6-sap-ha image derivation until images/family/rhel-9-6-sap-ha is available

concourse/pipelines/guest-package-build.jsonnet
Run each test task thrice before giving up. This is to handle flaky runs and quota exhaustion errors.
/cc @dorileo
=> Add retry attempts for each test tasks

packagebuild/daisy_startupscript_deb.sh
`PKGNAME` was renamed to `SOURCE_PKGNAME` in #1496
=> Use renamed variable in build script

packagebuild/daisy_startupscript_deb.sh, packagebuild/workflows/build_deb11.wf.json, packagebuild/workflows/build_deb11_arm64.wf.json, packagebuild/workflows/build_deb12.wf.json, packagebuild/workflows/build_deb12_arm64.wf.json, packagebuild/workflows/build_deb13.wf.json, packagebuild/workflows/build_deb13_arm64.wf.json, packagebuild/workflows/build_package.wf.json
This adds an optional variable that when set, can be used by the debhelper to build for specific Debian versions, but retain the previous behavior of building for "all" when it is not set.
=> Add support to target specific Debian versions in package build

concourse/pipelines/linux-image-build-dev.jsonnet
Now that it's in prod, we should remove it from dev so that the testing environments dont overlap
=> Remove Debian 13 from dev image build pipeline

concourse/pipelines/guest-package-build.jsonnet
Reverts GoogleCloudPlatform/guest-test-infra#1522 - this change is unrelated, pipeline is failing to pull containers with following permission error
```
ERRO[0000] checking origin bash failed: list repository tags: GET https://index.docker.io/v2/library/bash/tags/list?n=1000: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/bash Type:repository]] 
```
=> Revert "Revert "Add trigger field to package build job to customize whether it triggers off of commits""
